valyala/fasthttp

client.go
When using `fasthttp.Do()`, there is no resp return because client copy resp from respCopy inversely. For example in `testClientDoTimeoutError`:
```
var req Request
var resp Response
req.SetRequestURI("http://foobar.com/baz")
for i := 0; i < n; i++ {
err := c.DoTimeout(&req, &resp, time.Millisecond)
if err == nil {
t.Fatalf("expecting error")
}
if err != ErrTimeout {
t.Fatalf("unexpected error: %s. Expecting %s", err, ErrTimeout)
}
}
```
This PR fixed the bug here.
=> Fixed client copy resp from respCopy inversely

server.go
Hi @valyala 
When I test my fasthttprouter, I want to redirect a 307 request while you return a 302 response. I don't know what you consider about that. Wish your reply.
=> Redirect 307 instead of 302

header.go, header_test.go
Should fix #37
It replicates the logic in [header.go#L200](https://github.com/valyala/fasthttp/blob/master/header.go#L200)
Another way to fix this would be to assume default content-length: 0
Transfer-Encoding: identity appears to have been deprecated anyways
=> Don't assume Content-Encoding: identity when request is 1xx, 204 or 304

fasthttpadaptor/adaptor.go
I am not sure if this is the best fix for it, however without it the adaptor will just cause the process to crash.
I couldn't find string version of Path() so []byte to string conversion has to happen here.
=> fix fasthttpadaptor to work with http.ServeMux in Go 1.5

README.md
I was doing some benchmarking, comparing fasthttp and Varnish. Initially fasthttp was 5-10% slower than Varnish was (requesting a single url). However, after switching from Go 1.5 to 1.6 it was consistently 5-10% faster than Varnish. I figured a 15-20% performance improvement warrants a mention in the Readme.
Thank you for this amazing piece of work.
=> Readme: Suggest use of Go 1.6 for performance

uri.go, uri_test.go
Should fix #48. Since it appears that the URI.parse() function didn't deal with fragments unless there also was a query string
=> Fix parsing of fragments

reuseport/reuseport.go
If closing of an underlying File returns error, a Listener will not be returned to a user and will not be closed as well.
=> reuseport: close Listener

http.go
This adds a method to permit explicit freeing of memory.
```go
request := fasthttp.AcquireRequest()
response := fasthttp.AcquireResponse()
// ... stuff ... //
response.ReleaseBody(1024 * 1024)
fasthttp.ReleaseResponse(response)
fasthttp.ReleaseRequest(request)
```
---
Background:
I spent a fair bit of time this morning trying to figure out a memory leak, that wasn't.  This was in a  load generator replaying CDN traffic, with a mix of mostly small objects but the occasional large object.  
I was primarily baffled at the increasing number of objects that were 16M or 32M each, claimed by fasthttp.appendBodyFixedSize.  
```
(pprof) top 1
8.82GB of 9.21GB total (95.72%)
Dropped 218 nodes (cum <= 0.05GB)
Showing top 1 nodes out of 22 (cum >= 8.95GB)
flat  flat%   sum%        cum   cum%
8.82GB …
```
=> Add func (resp *Response) ReleaseBody(size int)

reuseport/reuseport.go
I am not sure if `rumprun` platform suppports it, but others mentioned in `build+` support
=> reuseport: set FD_CLOSEEXEC for the sockets

reuseport/reuseport.go, reuseport/reuseport_test.go
This enables support for "tcp6" network type allowing the reuseport package to use ipv6.
=> Enable IPv6 for reuseport

fasthttpadaptor/adaptor.go, fasthttpadaptor/adaptor_test.go
When incoming http.Request is constructed, "Transfer-Encoding" header is removed, and http.Request.TransferEncoding is set instead. See [`fixTransferEncoding()`](https://golang.org/src/net/http/transfer.go?h=fixTransferEncoding#L432).
This behaviour is now emulated in `fasthttpadaptor`.
=> Handle TransferEncoding in fasthttpadaptor

header.go
[RFC 2046](https://tools.ietf.org/html/rfc2046#section-5.1.1) allows for the boundary portion of the Content-Type header to be quoted. This was not being correctly handled. 
MultipartFormBoundary will now check for wrapping quotes, and remove them if present.
=> Fixed bug with quoted multipart form boundaries

server.go, server_test.go
See this issue: https://github.com/valyala/fasthttp/issues/126.
RequestCtx.userValues are not exported, but many times is useful to get all context's user values, exporting the .userValues is not a good idea because the key/value is request lifetime, with `VisitUserValues` the developer can copy these values and use anywhere he/she wants, test added.
=> Implement RequestCtx.VisitUserValues as requested

client.go, client_test.go
This fix relates to concurrent `DoTimeout/DoDeadline` using a `HostClient`: when there is no more free connection, as the `Request`'s body has been swapped, all subsequent calls will have an empty body.
I originally used `req.CopyTo` instead of swapping the body until I saw 3546c31: I think this solution should have a minimal impact on performance.
=> fix DoDeadline side effect when no free connection

client.go, client_test.go
Cannot follow redirect when using Do() but Get() doesn't expose `Request` object for fine-grain control.
This pull request adds `DoFollowRedirects(req *Request, resp *Response, maxRedirects int) error` method for making redirecting http request while having `Request` and `Response` objects exposed.
For more details, please visit issue #165.
All tests passed.
=> Redirection support for Do(*Request, *Response) for Issue #165

header.go
SetMethod appended directly to the `h.method` slice without setting its
length to zero, so multiple calls would create an unexpected value.
=> Make SetMethod slice to zero before appending

header.go, server.go, strings.go
There are 9 methods, but only 5 was supported. This is very stressful when implement RESTful API.
RFC about HTTP methods:
https://tools.ietf.org/html/rfc7231#section-4
https://tools.ietf.org/html/rfc5789#section-2
=> Add missing http methods

client_test.go
This should stop travis-ci from constantly failing with `"bind: address already in use"`.
=> Use random ports for tests

client_test.go
Prevents travis-ci from throwing:
```
client_test.go:489: unexpected error: listen tcp4 127.0.0.1:55234: bind: address already in use
```
=> Use and InmemoryListener for TestClientFollowRedirects

pprofhandler/pprof.go
Similar to [expvarhandler](https://github.com/valyala/fasthttp/tree/fc109d6887b5edb43510d924d14d735f3975fb51/expvarhandler) but for [net/http/pprof](https://golang.org/pkg/net/http/pprof/).
=> Add pprofhandler, fix #235

server.go
They still said the return value would be truncated to the nearest second which is false after ef10ed05a3797c2a387710e0a6d7dc62abc04290.
See: https://github.com/valyala/fasthttp/pull/379#issuecomment-414563486
=> Fix doc for some time functions

server.go
connTime never changes so the statement does nothing.
=> Remove code that does nothing

client.go
Support the same redirect status codes as the golang standard library
does: https://github.com/golang/go/blob/15095be9fbe726d4a3ef43b68d2fbc83e6484ded/src/net/http/client.go#L419
=> Fix supported redirect status codes

server.go, server_test.go
I'm still not sure if we should keep idle connections in a slice so we can close them on shutdown. It would prevent the issue where the server only shuts down after `ReadTimeout` seconds have passed. What do you think @kirillDanshin?
=> Add Server.Shutdown

header.go, http_test.go, server.go, server_test.go
his PR adds an option to the Server called `NoDefaultServerHeader` that
allows a user to indicate that neither the Server's `Name` field nor
the `defaultServerName` should be included in the Server's responses
as a `Server` header by default.
Now when `ResponseHeader.AppendBytes` is found to have an empty `server`
field, it simply skips the `Server` header. Previously that method
would write the `defaultServerName` when no value was found. The only
code paths that took advantage of that were ones originating from
`writeErrorResponse`, which now handles setting the server name
directly.
Fixes: https://github.com/valyala/fasthttp/issues/221
=> Allow removal of the Server header in responses

server_test.go
TestServerErrSmallBuffer had a small race condition where the test would checkout the output of the logger after the client connection had been served but before the worker had written the result to the logger.
This new code is also much faster as it doesn't actually use TCP but just some in memory buffers.
See https://travis-ci.org/valyala/fasthttp/jobs/420408931#0-935 for a failed sample
=> Stop random TestServerErrSmallBuffer failures

workerpool.go
fasthttp returns a 431 error when the request headers are too large. Most other HTTP servers do not log an error when the request header exceeds the limit. When serving HTTP requests directly to browsers, it is normal to occasionally hit the limit due to broken browsers or broken sites linking to your resource. These issues are generally outside of your control in the same way the already ignored errors are.
See https://github.com/erikdubbelboer/fasthttp/commit/eb78a50320f7b625ed9553294e83bc8fb76554d1
=> Do not log ErrSmallBuffer for request headers

client.go
The functions don't append to dst, they overwrite.
Fixes https://github.com/valyala/fasthttp/issues/154
=> Fix Get/Post documentation

server.go
Renaming a file can fail when the two files are on different devices. Just copy if rename fails for any reason. If rename fails because of other reaons copy will either work or fail for the same reason as well so we won't miss any errors after this.
Fixes https://github.com/valyala/fasthttp/issues/391
=> Copy file if rename fails (save multipart)

cookie.go, header.go, header_test.go
See: https://github.com/erikdubbelboer/fasthttp/issues/4
=> Add support for ResponseHeader.Peek("Set-Cookie")

http.go, http_test.go
There seems to be servers/load balancers that insert whitespaces between the chunk-size number and \r\n.
See: https://github.com/erikdubbelboer/fasthttp/issues/34
=> Allow whitespace after chunk size

compress.go
Now we have just the following methods that are able to gzip bytes and write it to a given `io.Writer`:
- `WriteGzip(...)`
- `WriteGzipLevel(...)`
- `AppendGzipBytes(...)`
- `AppendGzipBytesLevel(...)`
But the corresponding methods to deal with deflate-compression were missing:
- `WriteDeflate(...)`
- `WriteDeflateLevel(...)`
- `AppendDeflateBytes(...)`
- `AppendDeflateBytesLevel(...)`
=> Adding WriteDeflate[Level] and AppendDeflateBytes[Level] methods

client.go
The fix allows to configure retries attempts count for idempotent calls made by HostClient.
Motivation: a lot of API's do not treat PUT/DELETE/HEAD HTTP requests as idempotent that's why retrying of this calls can lead to serious behaviour issues.
=> Configuration for automatic retry for idempotent calls

bytesconv.go
I need to make ctx.Redirect() to doubleclick links. Example link is:
[https://ad.doubleclick.net/bla/bla/A1.B1;param1=val1;param2=val2;redir=?www.destination.com](url)
ctx.Redirect function was encoding ; to %3B and redirect were failing.
=> Add ';' to unescaped characters

bytesconv.go, uri_test.go
Fixes https://github.com/valyala/fasthttp/issues/256
=> Fix appendQuotedPath to include all allowed characters

client_test.go, cookie.go, cookie_test.go, header.go
This adds insensitive comparisons for headers and cookies keys.
Fixes https://github.com/valyala/fasthttp/pull/230 and https://github.com/valyala/fasthttp/issues/409.
=> Do case insensitive comparisons for headers and cookies

bytebuffer.go, bytesconv.go
Found using https://go-critic.github.io/overview#deprecatedComment-ref
=> use proper "Deprecated" comment format

pprofhandler/pprof.go
Improve #243 to support all named profiles like heap, goroutine, threadcreate, mutex, block, allocs, and possibly other names in the future.
Tested with the following to also verify the web UI:
```go
func main() {
router := fasthttprouter.New()
router.GET("/debug/pprof/:name", pprofhandler.PprofHandler)
router.GET("/debug/pprof/", pprofhandler.PprofHandler)
log.Fatal(fasthttp.ListenAndServe(":8080", router.Handler))
}
```
=> Add support for named profiles like heap, goroutine, threadcreate, etc.

header.go, server.go, workerpool.go
This implementation allows user to handle crypto/tls.Config.NextProtos to use their own handlers for the negotiated TLS protos like HTTP/2.
Workerpool where changed to adapt WorkerFunc to another conns server with ServeConn type and contains the Server structure which is used to check configured protos.
=> Added Server.nextProtos

header.go, header_test.go
I'm not sure about this one. At first it was ok but because of the messy header parsing and returning this turned out to be buggy and required some fixes to get working properly. I also don't like the test, it seems to test a lot more than is required for the code changes.
See: https://github.com/erikdubbelboer/fasthttp/issues/18, https://github.com/erikdubbelboer/fasthttp/pull/27, https://github.com/erikdubbelboer/fasthttp/pull/29 and https://github.com/erikdubbelboer/fasthttp/pull/40
=> Add RequestHeader.RawHeaders()

http.go, http_test.go
[CreateFormFile](https://golang.org/pkg/mime/multipart/#Writer.CreateFormFile) always set `Content-Type` header to `application/octet-stream`.
Use [CreatePart](https://golang.org/pkg/mime/multipart/#Writer.CreatePart) instead so all headers in the multipart form can be used.
=> Use form headers in WriteMultipartForm

server.go
Hello.
We need to monitor how many incoming concurrent do we have at a moment. So we need a method like this one. It would be nice if you merge it :)
=> Added method (*Server).GetCurrenctConcurrency()

server.go
As you can see here https://golang.org/src/crypto/tls/conn.go#L1041
crypto/tls.Conn does not perform a TLS handshake until Read or Write functions are called.
Then the solution is to call crypto/tls.Conn.Handshake() to check Client values.
Solves https://github.com/valyala/fasthttp/issues/453
=> Fixed NextProto error caused by non-Handshake call.

nocopy.go
I've tried that if `noCopy` does not implement the `sync.Locker` interface, go vet will not work. see:
```bash
$ cat main.go 
package main
type noCopy struct{}
func (*noCopy) Lock() {}
//func (*noCopy) Unlock() {}
type Demo struct {
noCopy noCopy
}
func Copy(d Demo) {}
func main() {
d := Demo{}
Copy(d)
}
$ go vet main.go
```
implement `sync.Locker` interface:
```bash
$ cat main.go 
package main
type noCopy struct{}
func (*noCopy) Lock() {}
func (*noCopy) Unlock() {}
type Demo struct {
noCopy noCopy
}
func Copy(d Demo) {}
func main() {
d := Demo{}
Copy(d)
}
$ go vet main.go 
./main.go:13: Copy passes lock by value: main.Demo contains main.noCopy
./main.go:17: call of Copy copies lock value: main.Demo contains main.noCopy
```
=> fix go vet do not work on noCopy

nocopy.go
Fix https://github.com/valyala/fasthttp/pull/460/commits/02d006acf71a963d0568172d54de893bd147f3fc#diff-3b5fdea3b153cacd75dfcc26d1fe6617R11
```bash
$ cat main.go
package main
type noCopy struct{}
func (*noCopy) Lock() {}
func (*noCopy) UnLock() {}
type Demo struct {
noCopy noCopy
}
func Copy(d Demo) {}
func main() {
d := Demo{}
Copy(d)
}
$ go vet main.go
$
```
```bash
$ cat main.go
package main
type noCopy struct{}
func (*noCopy) Lock() {}
func (*noCopy) Unlock() {}
type Demo struct {
noCopy noCopy
}
func Copy(d Demo) {}
func main() {
d := Demo{}
Copy(d)
}
$ go vet main.go
./main.go:13: Copy passes lock by value: main.Demo contains main.noCopy
./main.go:17: call of Copy copies lock value: main.Demo contains main.noCopy
```
=> noCopy does not implement sync.Locker well. L letter of Unlock must be lower case

header.go, server.go
Don't return an error response if a keep-alive connection closes either because the other side closed the connection or a read timeout occurs.
This will prevent net/http from printing
`Unsolicited response received on idle HTTP channel`
when a ReadTimeout is set on the fasthttp Server.
Fixes #465
=> No error response on keep-alive close

server.go
The method `(*Server).GetOpenConnectionsCount()` is required for our monitoring system
The option `DisableSleepWhenConcurrencyLimitsExceeded` is required in our high-load application. This `Sleep()` caused some problems in our infrastructure when servers were overloaded so we'd like to be able to disable it if possible :)
=> Added method (*Server).GetOpenConnectionsCount() and option DisableSleepWhenConcurrencyLimitsExceeded

cookie.go, cookie_test.go, strings.go
This is an implementation of the `SameSite` attribute for cookies. It is inspired by go v1.11's `net/http` implementation of the SameSite attribute, seen here: https://golang.org/src/net/http/cookie.go?s=4244:4276#L214
This PR addresses issue #489.
=> Support SameSite cookie attribute

header.go, header_test.go
Fixes #486
I'm actually wondering if we should just change `VisitAll` to use this code instead. The current code for `VisitAll` was written before `rawHeaders` was added and now goes though all kinds of hoops to put things like the cookie header back together. My benchmark below shows that VisitAllInOrder is only slightly slower. @kirillDanshin what do you think?
```
BenchmarkVisitAllInOrder-8   	10000000	       141 ns/op	       0 B/op	       0 allocs/op
BenchmarkVisitAll-8          	30000000	      44.5 ns/op	       0 B/op	       0 allocs/op
```
=> Add RequestHeader.VisitAllInOrder

cookie_test.go, fs.go
This fix is based on suggestion of "prealloc" static analysis tool [1].
Per note of the tool's author suggestion, its recommended to allocate the
slice length/capability, if we known their possible size.  This is to
minimize "append" to re-allocate the slice underlying array.
[1] https://github.com/alexkohler/prealloc
=> all: pre-allocated slice with possible known size

args.go, client_test.go, fs.go, fs_test.go, http_test.go, server.go
Changes:
07f0c88 (Shulhan, 2 hours ago)
all: simplify variable initialization
If we assign the variable after declaring it, we can simplify it using
":=" operator or "= value". The reader can still known the type of variable
from the struct name or variable type before assignment operator.
7e00ec6 (Shulhan, 2 hours ago)
args: simplify if-condition check on boolean value
cf6c51e (Shulhan, 2 hours ago)
http_test: simplify strings.Index with strings.Contains
Both have the same O(n), but strings.Contains more readable on
if-condition.
8439088 (Shulhan, 2 hours ago)
all: replace string(bytes.Buffer.Bytes()) with bytes.Buffer.String()
Although its only occured on test files, it may be worth to simplified it.
5f1f929 (Shulhan, 2 hours ago)
all: use sort.Strings when applicable
Basically, …
=> Various changes regarding code readibility

client.go
Addressing https://github.com/valyala/fasthttp/issues/529 , shouldn't break anything.
=> SkipBody is propagated to Response copy

client.go
We need to dynamically change a `MaxConns` value. So this patch is about safe atomic reading from `MaxConns`.
=> An atomic approach for HostClient.MaxConns

http.go, http_test.go
=> Support huge read-only []byte response bodies

server.go
Signed-off-by: Kirill Danshin <kirill@danshin.pro>
=> reset request before ctx release; fixes #548

server.go, server_test.go
- Improved timing code to be much cleaner
- Add IdleTimeout
- Remove obsolete optimization (was fixed in Go 2 years ago: https://github.com/golang/go/issues/15133#issuecomment-271571395)
Fixes #563 and potentially #491
=> Timing fixes

http.go, http_test.go
In case of body stream if first body bytes generation takes long this adds an option of "faster response".
Will add tests if general idea is ok.
=> Option for immediate header flush

server.go
Yes, normally, there is no need to change the status code, following the rules of HTTP.
However, some business scenarios may be needed, and I think fasthttp, as a network base library, should give control to the developers.
Because our business will need to timeout the request, return 204 status code
_Originally posted by @losingle in https://github.com/savsgio/atreugo/issues/22#issuecomment-499210079_
=> ADD TimeoutWithCodeHandler support

cookie.go, cookie_test.go, strings.go
As you may have heard Google recently announced changes coming to Chrome with the release of version 76 in July 2019. This change will directly impact the handling of 3rd party cookies.
For Chrome, set the cookie attribute “SameSite = None”, so that your cookie will be sent in the third party context. Leaving the attribute of “SameSite” unspecified would result in your cookie not being sent in case the user enables the “same-site-by-default-cookies” setting in their browser.
Set "SameSite = None"  is required is this case alongside "Secure"
You can find more detailed information here: 
https://tools.ietf.org/html/draft-west-cookie-incrementalism-00
https://blog.chromium.org/2019/05/improving-privacy-and-security-on-web.html
=> Support SameSite value "None" cookie attribute

header.go, header_test.go
At the moment if one configures `NoDefaultContentType` and does not configure any `Content-Type` header (through any of the appropriate header methods), `fasthttp` outputs an invalid header with an empty value, i.e. `Content-Type: `
This small patch fixes this case.
=> Correctly handle `NoDefaultContentType` without setting an `Content-Type` value

allocation_test.go, client_test.go, http.go, strings.go, uri.go
=> Add support for user:pass in URLs

bytesconv.go
A faster s2b function
The new function just use the return stack space to store the final value, without the allocation of a temporary struct. s2bFast is 100% faster if the Go compiler doesn't use deeper optimization in some code, if there is deeper optimization (inline for example), s2bFast is 5%~15% faster. The s2bFast is always same as s2b in any situations, both functions identically from the perspective of caller. You can see this in ASM, the new one has a smaller stack space and without locals.
Environment:  go1.12.7 darwin/amd64
(The go code)
> func s2b(s string) []byte {
sh := (*StringHeader)(unsafe.Pointer(&s))
bh := SliceHeader{
Data: sh.Data,
Len:  sh.Len,
Cap:  sh.Len,
}
return *(*[]byte)(unsafe.Pointer(&bh))
}
> func s2bFast(s string) (b []byte) {
bh := …
=> A faster s2b function

client.go
Hello! First, thank you for maintaining this great library!
I stumbled recently upon this description of `fmt.Sprintf("%s:%d", addr, port)` as an anti-pattern: https://github.com/golang/go/issues/28308 - it seems to apply here.
=> Use ipv6-compliant methodology for joining host port

client.go
As a next step from https://github.com/valyala/fasthttp/pull/532, as in comments @xuecai mentioned an issue with it being overwritten by .Reset() and future check.
=> Propagating custom SkipBody value to allow skipping body for non-HEAD requests

fasthttputil/inmemory_listener_test.go, fasthttputil/pipeconns.go
When requests are made from `http.Client` to `http.Server` through `fasthttp.InmemoryListener`, data race occurs. Also, when `fasthttp.Server` is used for the server side instead of `http.Server`, which might be common for testing programs using this lovely library, the same thing happens.
This might be because `pipeConn` implemented in `fasthttputil/pipeconns.go` does not conform to [net.Conn](https://golang.org/pkg/net/#Conn) which states that "Multiple goroutines may invoke methods on a Conn simultaneously." 
Specifically, the data race I have found occurs when `pipeConn.Read` and `pipeConn.SetReadDeadline` are called concurrently. 
This PR includes the following.
- Add tests to reproduce the data race.
- To reproduce, please go one commit back.
- Add one lock to stop the data race …
=> Fix data race in fasthttputil.pipeConn

bytesconv.go
In this case, indexed read of the table is faster than calculate the result
(benchmark result)
BenchmarkHexString-8    2000000000               0.65 ns/op
BenchmarkHexCharUpeer-8        500000000                3.77 ns/op
(benchmark codes)
```
var r byte
func BenchmarkHexString(b *testing.B) {
testSlice := make([]byte, 0, b.N)
for i := 0; i < b.N; i++ {
testSlice = append(testSlice, uint8(rand.Uint32()))
}
b.ResetTimer()
for i := 0; i < b.N; i++ {
r = "0123456789ABCDEF"[testSlice[i]>> 4]
}
}
func BenchmarkHexCharUpeer(b *testing.B) {
testSlice := make([]byte, 0, b.N)
for i := 0; i < b.N; i++ {
testSlice = append(testSlice, uint8(rand.Uint32()))
}
b.ResetTimer()
for i := 0; i < b.N; i++ {
r = hexCharUpeer(testSlice[i] >> 4)
}
}
```
=> Replace hexCharUpeer with upperhex

bytesconv.go, bytesconv_timing_test.go
int2hexbyte can be replaced with lowerhex, and i'm wandering maybe we could use only one HEX format, since the constant upperhex is already exists.( If use upperhex only, we need to modify our test instead)
Also replace 15 with 0xf in take the 4 LSBs in byte, maybe 0xf looks more readable in this case?
=> Replace int2hexbyte with lowerhex

client.go
Refactoring to reuse response status codes.
Status codes are needed, where we ourselves implement a cycle for all redirects.
To understand where the last redirect is.
=> Refactoring to reuse response status codes

client.go, client_test.go
See the test for context - basically I have a URL like http://google.com/encoded/Y%2BY%2FY%3D/stuff, but when I use fasthttp, due to path normalization the actual request that gets made is to http://google.com/encoded/Y+Y/Y=/stuff.  On some servers (e.g. fasthttp's server), these URLs are semantically equivalent, but on some servers (e.g. those google urls) they are not. If you click through those URLs you can see the difference in the 404 page that google returns. https://stackoverflow.com/questions/1957115/is-a-slash-equivalent-to-an-encoded-slash-2f-in-the-path-portion-of-a has some more context on the server-side situation as well.
This wires https://github.com/valyala/fasthttp/pull/649 through the client layer to solve this issue.
=> Allow client to disable path normalization

fasthttputil/inmemory_listener.go
There are three identical errors in inmemory_listener.go, maybe we could use errInmemoryListenerClosed to replace them.
=> fasthttputil: add errInmemoryListenerClosed

args_test.go, bytesconv_test.go, header_test.go, reuseport/reuseport_test.go, server.go, stackless/writer_test.go
Format errors and fix some typos, according to https://github.com/golang/go/wiki/CodeReviewComments#error-strings
=> Format errors

http.go
=> fix: when multipartform  no data,FormValue do not need panic

server_test.go, workerpool.go
**Steps to Reproduce**
1. Run [hello world example](https://github.com/valyala/fasthttp/blob/master/examples/helloworldserver/helloworldserver.go) 
2. Send request with timeout where the value of the `content-length` request header exceeds length of the request body.
```
curl 'http://localhost:8080/' -X "POST" -H 'content-length: 5' -d "123" --max-time 1
```
**Actual Behavior:**
- Server logs unexpected EOF.
```
2019/10/26 18:11:57 error when serving connection "127.0.0.1:8080"<->"127.0.0.1:58492": unexpected EOF
```
**Expected Behavior:**
- Server logs no error (matching behavior of net/http).
---
See #660
=> Requests with incomplete bodies no longer cause log noise

tcpdialer.go
Right now default TCPDialer is forced to use default net.LookupIP(), which always uses default mechanism, like looking through "/etc/resolv.conf" on *nix. This request allows specifying a custom resolver that may be used for more flexible querying.
=> Ability to pass custom DNS resolver to TCPDialer

header.go, server.go
sync.Once only has the overhead of a single atomic.LoadUint32
Fixes #693
=> Don't start a goroutine when not needed

tcpdialer.go
Continuing the work started at https://github.com/valyala/fasthttp/pull/689/files . 
Turns out, specifying custom resolver doesn't allow to avoid resolving completely (as `Dial()` has to return a connection to a DNS server), so in this way it becomes possible to reimplement `LookupIPAddr()` function to specify resolved name manually or get it from some place other than actual DNS query.
=> Custom LookupIPAddr function

client_test.go, header.go, header_regression_test.go, header_test.go, http.go, http_test.go, server.go, server_test.go
This means we can't skip parsing headers for GET requests anymore. This
can be seen as good as it also allows us to reject malformed GET
requests, something we didn't do before this. Performance also isn't
affect much:
```
benchmark                                            old ns/op     new ns/op     delta
BenchmarkClientGetEndToEnd1Inmemory-16               640           641           +0.16%
BenchmarkClientGetEndToEnd10Inmemory-16              713           710           -0.42%
BenchmarkClientGetEndToEnd100Inmemory-16             732           749           +2.32%
BenchmarkClientGetEndToEnd1000Inmemory-16            759           774           +1.98%
BenchmarkClientGetEndToEnd10KInmemory-16             785           808           +2.93%
BenchmarkNetHTTPClientGetEndToEnd1Inmemory-16 …
```
=> Allow a body for GET requests

header.go, header_test.go
=> add extra checking of header buffer, to support multi line header value

server.go, server_test.go
At the moment there is always a HTTP response before the connection gets
hijacked. This second option to Hijack() prevents this response from
being send.
Fixes: https://github.com/valyala/fasthttp/issues/698
=> Allow no response to be send when a connection is hijacked

server.go
It is confusing that defaultErrorHandler returns "Error when parsing request" when request timeout.
=> Set StatusRequestTimeout when net timeout error occurred

fasthttpadaptor/adaptor.go, fasthttpadaptor/adaptor_test.go
Right now the request in fasthttpadaptor has a background context. It would be beneficial to set it to `fasthttp.RequestCtx` or at least forward values that are already set in the context. This would allow us to retrieve any value that was set in middleware before the request reached the `http.Handler`.
=> Forward context in fasthttpadaptor

client.go, client_test.go, fasthttputil/pipeconns.go, header.go
Not ErrConnectionClosed which is incorrect.
Fixes: https://github.com/valyala/fasthttp/issues/355
=> Client should return ErrTimeout on timeout

header.go, header_test.go, server.go, server_test.go
same as https://github.com/valyala/fasthttp/pull/629  but with tests.
=> Add support for `NoDefaultDate` option that excludes the sending of the `Date` header

prefork/prefork.go
The main process will exit if one of the prefork child processes doesn't complete successfully under the current prefork mode, so it ought to make sure that all child processes run independently and the main process will only exit after all child processes are finished.
=> Make the prefork mode more robust

client.go, client_test.go
This commit adds a `DoRedirects` method to both `HostClient` and
`Client` as well as top level convenience function of the same name that
is called with the package level `defaultClient`.
Re-implementing this redirect logic in user code is harder than
necessary.
For context, this is the first of possibly many PRs that I'm contributing as part of my effort to integrate Vegeta with this library. See https://github.com/tsenart/vegeta/pull/500
=> client: Implement DoRedirects

server.go, server_test.go
Hello,
It can be the case when the hijackerHandler is not set but hijackNoResponse is. If that case happens before this commit the server won't send any response to the client and then the connection will hang (client will be waiting, the server will be waiting too).
Thanks.
=> Fixed case when no hijacker is added but no-response is true

http.go, http_test.go, server.go
Some servers want to treat the multipart form data as a binary blob, or at least not read/parse it until other decisions are made about the request.
=> Add configuration to not pre-read multipart form data

client_test.go, uri.go, uri_test.go
This is the same as `net/http` does.
Fixes #788
=> Don't allow ASCII control character in URLs

server.go, server_test.go
Fixes https://github.com/valyala/fasthttp/issues/783
An okay solution right now which allows servers to deny reading the request body after reading the request headers via a server callback configuration.
A more long term solution later on might be to give full control to the user during their handler callback, but that would definitely require a lot more work and be more error prone for the user.
One unfortunate issue with this is, if you do any major work in processing headers before accepting or denying a request, you likely will have to re-process the headers on the other side.  It might be worth sticking a
````
func() interface[}
````
callback out of the deny which can be passed to a new handler, so people can pass state between the two.
=> allow the expect 100 continue workflow to deny requests

client.go
This avoids the req.Header.userAgent sharing an underlying array with the
global defaultUserAgent
This should fix the #795
=> Copy to the req.Header.userAgent from the defaultUserAgent

client.go, client_test.go, http.go
`HostClient` connects to its host though either HTTP or HTTPS. It should never switch between protocols. This breaks the `HostClient` maps inside `Client`. There are two maps there:
`m` is for http HostClients
`ms` is for https HostClients
Updating a http `HostClient` to https, while it is still inside map m will make all future requests to the given http host go to https. Since servers can serve different content on both ports this can break things.
Thats why from now on `HostClient` will throw and error when it is used outside `Client` and tries to follow a redirect to a different protocol.
=> Backwards incompatible! HostClient can't switch between protocols

client.go, client_test.go
Fixes https://github.com/valyala/fasthttp/issues/832
=> Restart PipelineClient worker on error

status.go, status_test.go, status_timing_test.go
We use slice instead of map to store all status messages and status lines. But for the status code bigger than `statusMessageMax(511)`, it still should store them in the dynamic map(`invalidStatusLines`).
@erikdubbelboer PTAL
benchmarks result:
OLD:
```
BenchmarkStatusLine99
BenchmarkStatusLine99-8         278959663                4.51 ns/op            0 B/op          0 allocs/op
BenchmarkStatusLine99-8         262258332                4.83 ns/op            0 B/op          0 allocs/op
BenchmarkStatusLine99-8         257144448                4.73 ns/op            0 B/op          0 allocs/op
BenchmarkStatusLine99-8         251641419                4.80 ns/op            0 B/op          0 allocs/op
BenchmarkStatusLine200
BenchmarkStatusLine200-8        257207306                4.64 ns/op …
```
=>  improve statusLine and StatusMessage by using slice instead of map

fs.go, fs_test.go
https://github.com/valyala/fasthttp/issues/829#issuecomment-640252501
I did what @Fenny suggested with his help, though I can make it prioritize brotli compression by default if that's better.
=> Brotli support in FS handler.

http.go
I know doing this causes some kind of code duplication but I was writing `[]byte` directly into the response and converting`[]byte` to `string` and again `string` to `[]byte` caused a little process and delay for my large data. And I think reusing a code just adds inconvenience in this case.
=> remove unnecessary type conversion

fasthttpproxy/proxy_env.go
There is a bug with req url schema settings in the proxy dialer adapter.
=> fixed default schema for for req url

tcpdialer.go
Add nil check for TCPDialer's LocalAddr. The PR will improve the error message for dial failure when LocalAddr is not set.
```
err: dial tcp4 <nil>->127.0.0.1:8080: connect: connection refused
err: dial tcp4 127.0.0.1:8080: connect: connection refused
```
=> add nil check for TCPDialer LocalAddr

http.go
I think `uint32` is enough(4GB) for current situation.
And here is the benchmark result:
Test case
```go
func BenchmarkRound2(b *testing.B) {
b.RunParallel(func(pb *testing.PB) {
b.ReportAllocs()
b.ResetTimer()
for pb.Next() {
round2(0x10001)
}
})
}
```
OLD:
```hs
BenchmarkRound2-16      1000000000               0.875 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.880 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.874 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.876 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000               0.874 ns/op           0 B/op          0 allocs/op
BenchmarkRound2-16      1000000000 …
```
=> Improve round2 performance

args.go, args_test.go
In a HTTP Request Headers/QueryArgs can have multiple values for the same key. Currently [delAllArgs](https://github.com/valyala/fasthttp/blob/master/args.go#L387-L399) doesn't delete all the headers/queryargs with the same key. This change fixes it by setting the index `i` to be checked next for deletion, correctly.
I have extracted relevant parts of code in [playground](https://play.golang.org/p/JmE2-Y8vz2k) to show the before and after changes.
=> Fixing deletion of headers/queryargs having multiple values.

http.go, server_test.go
Co-authored-by: Fenny fenny@gofiber.io
Related to #911
=> Add test cases for StreamRequestBody

uri.go, uri_test.go
https://github.com/valyala/fasthttp/issues/919
=> Use QueryString while constructing RequestURI instead of QueryArgs if parsedQueryArgs is set to false

bytesconv.go
The `go vet` will complain about `sh := *(*reflect.StringHeader)(unsafe.Pointer(&s))` (possible misuse of reflect.StringHeader). The extra `*` is added because it generate less code compared to `sh := (*reflect.StringHeader)(unsafe.Pointer(&s))`, see details in https://godbolt.org/z/xG3hbn   
They are actually do the same thing for now(almost same speed, previous implementation 1 CPU tick faster maybe), but if `go vet` complain about this, i think we can remove the extra `*` to prevent later Go release has inconsistent behavior(escape analysis etc).
=> fix s2b go vet warning

http.go, server_test.go, streaming.go, streaming_test.go
- Allow DisablePreParseMultipartForm in combination with
StreamRequestBody.
- Support streaming into MultipartForm instead of reading the whole body
first.
- Support calling ctx.PostBody() when streaming is enabled.
=> Streaming fixes

compress.go
Add compatibility with flate.Reader to reduce allocations of bufio.NewReader structs backed by default size slices of 4096 bytes for WriteGunzip, WriteDeflate.
=> byteSliceReader compatibility with flate.Reader interface

client.go, client_test.go
This PR fixes the unexpected panic issue when calling `Do()` of a `PipelineClient` with nil `Response` parameter.
And a new test case is added to avoid we run into similar issues in the future.
closes #996
=> Fix unexpected panic when calling Do of a PipelineClient

client.go
@erikdubbelboer In case if #992 will be implemented, my fix almost (but may improve reusability of pools anyway, less number of objects inuse) won't needed, because of hostclients reused both with internal to HostClient pools, looking forward to one of our patches.
=> Improve Client/HostClient pooling when many HostClient structs created and removed during program execution

client.go, header.go, header_test.go, http.go, server.go
For some applications handling sensitive data, it can violate certain certifications, such as HIPAA, to log parts of requests and responses like the header and body.
This PR adds the option `SecureErrorLogMessage` which will replace the fully detailed error messages with more generic ones so that they can safely be logged.
=> Adding support for securing error logs

server.go, server_test.go
=> Add option for middleware to set custom remote address

http.go, streaming.go, streaming_test.go
`io.Reader` interface provided by `requestStream` is broken for chunks exceeding `len(p)` which can lead to various panics in code using `Read()`.
=> Fix chunked streaming

fasthttpadaptor/adaptor.go
Fix(adaptor): Fixed an issue where the adapter did not convert all values of the header successfully when converting the header.
Change `Header.Set()` to `Header.Add()` to support header that has multiple values such as `Accept`
Relative reference: https://github.com/gofiber/fiber/issues/1329
=> Fix adaptor doesn't convert header values correctly

http.go, http_test.go
Come from #1019  @erikdubbelboer I added test to prove my changes work. I'm not always removing `Content-Length` header, I remove it when `contentLength == -2` which means no body. 
This is not a perfect solution, because I found If any `Request.SetContentLength` is called then `contentLength` must be printed when `RequestHeader.Write`. I suppose we may define -3 or sth don't set `contentLengthBytes` any more.
Shall we close MR only after we have the same conclusion?
=> Fix ignoreBody still set content length

fasthttpadaptor/adaptor.go, fasthttpadaptor/request.go
To easy method to convert ctx.RequestCtx to http.Request
=> feature: add ConvertRequest func

header.go, header_test.go, strings.go
refer to https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.5 
> A sender that generates a message containing a payload body SHOULD
generate a Content-Type header field in that message unless the
intended media type of the enclosed representation is unknown to the
sender.  If a Content-Type header field is not present, the recipient
MAY either assume a media type of "application/octet-stream"
([RFC2046], Section 4.5.1) or examine the data to determine its type.
default content type should be "application/octet-stream" instead of "application/x-www-form-urlencoded" which will mess body up.
I found this because when I sent curl command like `curl my/proxy/with/fasthttp -d abcd -XPOST` I noticed content-type had been modified by fasthttp to `application/x-www-form-urlencoded`, and …
=> Use proper content-type when it is not present

fasthttpadaptor/adaptor_test.go, header.go, header_test.go
These functions should take the headers that are handled differently into account.
Fixes #1033
After this change it is not possible to have multiple 
Content-Type, Content-Length, Connection, Server, Set-Cookie, Transfer-Encoding and Date headers. Having other headers multiple times is still fine. For these headers it should never happen anyways and I don't think we have any users who do this. But if they do it would break for then.
=> Fix header .Add functions

client.go, client_test.go
Solves https://github.com/valyala/fasthttp/issues/972
=> Defined Transport for the client

tcpdialer.go
TCPDialer{} extended to support DNSCacheDuration
=> TCPDialer :: DNSCacheDuration option

header.go, server.go, server_test.go
Don't wait for the next request as this can take some time, instead
flush the outstanding responses already.
Fixes #1043
=> Flush buffered responses if we have to wait for the next request

server.go, server_test.go
`ResetUserValues()` function will allow users to reset the user values from RequestCtx.
=> Add ResetUserValues() and related test

server.go, server_test.go
=> Handle perIPConn in RequestCtx.IsTLS() specially

fs_test.go, server_test.go
These tests keep giving errors because Windows Actions are slower.
=> Fix various Windows Github Action errors

server.go, server_test.go
Fixes https://github.com/valyala/fasthttp/issues/1080
=> Various deadline fixes

README.md
Now that the Github dependency graph is available：https://github.com/valyala/fasthttp/network/dependents?package_id=UGFja2FnZS0yMjY0ODE2OTU2, we don't need this badge anymore.
=> Remove the redundant badage

.gitignore, status.go
we  create  a  new `[]byte` by   appending ` []byte` directly  instead of  ` fmt.Sprintf `+`[]byte(str)` . it  not only reduce memory allocation ,but also improve performance.
benchmark result:
- old
```
$tyltr > go test -benchmem -run=none  -bench=BenchmarkStatusLine512 -count 10
goos: darwin
goarch: amd64
pkg: github.com/valyala/fasthttp
BenchmarkStatusLine512-8        12142441               109 ns/op             120 B/op          4 allocs/op
BenchmarkStatusLine512-8         8737126               126 ns/op             120 B/op          4 allocs/op
BenchmarkStatusLine512-8         9828290               108 ns/op             120 B/op          4 allocs/op
BenchmarkStatusLine512-8        12083548               106 ns/op             120 B/op          4 allocs/op
BenchmarkStatusLine512-8 …
```
=> improve invalidStatusLine by  appending a `[]byte` directly

client.go, header.go, header_timing_test.go, strings.go
improve `IsMethod`  i.e `IsPost` 、 `IsGet ` and  so on.
benchmark
- old
```
goos: linux
goarch: amd64
pkg: github.com/valyala/fasthttp
cpu: Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
BenchmarkRequestHeaderIsPost-2          559623241                2.003 ns/op           0 B/op          0 allocs/op
BenchmarkRequestHeaderIsPost-2          604524886                1.992 ns/op           0 B/op          0 allocs/op
BenchmarkRequestHeaderIsPost-2          601059054                2.015 ns/op           0 B/op          0 allocs/op
BenchmarkRequestHeaderIsPost-2          605856414                2.006 ns/op           0 B/op          0 allocs/op
BenchmarkRequestHeaderIsPost-2          606804846                1.981 ns/op           0 B/op          0 allocs/op
BenchmarkRequestHeaderIsPost-2 …
```
=> feat: improve IsMethod 

userdata.go
I  dont think it is necessary  to  store  key & value into  `userdata ` ,when value  is  `nil` . 
-  method `Get` will  return  nil , if  key does not  exist.    same result with not    storing  key & value into  `userdata `.
-  there is not  a flag  indicates whether value was found in the   `userdata ` . for example ` func (d *userData) Get(key string) (value interface{} , exist bool )`
=> feat:no  need  to  store nil

client.go, fs_test.go, server_test.go
It's too slow and gives a lot of false positives in our tests.
=> Don't run all race tests on windows

fs.go
The same as the pull request of https://github.com/valyala/fasthttp/pull/1106,in the fileslockmap read is more than write ,so sync.map will be better
=> use sync.map is better

http.go, http_test.go
Currently, the only way to set URI for a request is to call SetRequestURI(string).
Then when a request performed the string will be parsed into a fasthttp.URI struct.
If there are many requests with the same URI then we'll waste CPU for a parsing of the same URI string.
With the new SetURI(*URI) method we can once parse a URI string into a fasthttp.URI struct and then reuse it for many requests.
Unfortunately the URI will be copied because may be modified inside the request.
But anyway this will be more lightweight than parsing.
=> http.go: Request.SetURI() (Fix #1141)

client.go, server_test.go, uri.go, uri_test.go
Use them instead of manual schema comparison.
This makes code cleaner but also opens a door for next optimizations
=> uri: isHttps() and isHttp()

README.md
=> Add string and bytes buffer convert trick in README

server.go, server_test.go
=> feat: close idle connections when server shutdown

server.go, server_test.go
This fix the use cases that reference a `RequestCtx` into user values that implements `io.Closer`
Example:
```go
func handler(ctx *fasthttp.RequestCtx) {
rd := acquireRequestDuration()
rd.ctx = ctx
rd.start = time.Now()
ctx.SetUserValue("__http::requestDuration__", rd)
}
func (rd *requestDuration) Close() error {
duration := time.Since(rd.start)
statusCode := strconv.Itoa(rd.ctx.Response.StatusCode())
method := string(rd.ctx.Request.Header.Method())  // ISSUE: INVALID VALUE
path := string(rd.ctx.Request.URI().Path())  // ISSUE: INVALID VALUE
requestsDurationHistogramVec.WithLabelValues(
statusCode, method, path,
).Observe(duration.Seconds())
releaseRequestDuration(rd)
return nil
}
```
=> fix: reset request after reset user values on keep-alive connections

server.go, server_test.go
Same as the issue https://github.com/valyala/fasthttp/pull/1162 but with the response!
=> fix: reset response after reset user values on keep-alive connections

http.go, http_test.go
Allow to change Host header when using Client. Currently only HostClient allows to change Host header.
=> Allow to set Host header for Client

http.go, http_test.go
Added UseHostHeader support for client.DoTimeout.
=> Fix UseHostHeader for DoTimeout + tests

http.go, http_test.go
And more tests for UseHostHeader
=> Release UseHostHeader in ReleaseRequest()

server.go, server_test.go
Related PR: https://github.com/valyala/fasthttp/pull/1199
=> fix(hijack): reuse RequestCtx

uri.go
i  dont think  it  is  necessary to  clean  `slice`   after ` dst.Reset() `
=> remove redundant code

client_test.go, server_timing_test.go, uri_test.go
To simplify understanding of test use more meaningful names instead of asdf
=> uri_test.go use example.com for clearness

client.go
ConfigureClient configures the fasthttp.HostClient. 
So I can use https://github.com/dgrr/http2 in fasthttp.Client
=> support configure HostClient

header.go, header_test.go
#873
In the definition of restful style api, the deletion of resources is generally defined as follows: 
```go
delete /students/{student_id}
```
there is no need to pass in a body, so add a func SetNoDefaultContentType to RequestHeader.
=> RequestHeader support set no default ContentType

server.go
The header can't be both a HEAD and GET so checking both doesn't make any sense.
=> fix: (useless check), skip Response body if http method HEAD

fs.go, server.go
See: https://github.com/valyala/fasthttp/issues/1226
=> Warn about unsafe ServeFile usage

http.go
add request and response body size limit, it prevents the large body from slowly stretching the memory of the entire service
=> feature: Keep the memory usage of the service at a stable level

reuseport/reuseport_test.go, server_test.go, uri_test.go
Just ignore /../ tests on windows until we have proper suppor.
=> Fix windows tests

server.go
`RequestCtx`'s are reused in a server specific pool, so no need to reset it. This fixes a use after reset but when `RequestCtx` is use as context.
Fixes #1205
=> Don't reset RequestCtx.s

client.go, client_test.go, client_unix_test.go, http.go, tcp.go, tcp_windows.go
=> Read response when client closes connection #1232

client.go
Fixes #1236 
* At first, we implement LIFO(conventional) and FIFO which indicate in #1236
=> Add connection pool queuing strategies in HostClient.

bytesconv_32.go, bytesconv_32_test.go, bytesconv_64.go, bytesconv_64_test.go
The bytesconv 32-bit tests fail on s390x, because it is a 64-bit
architecture. Add the appropriate build flags so that 32-bit tests do
not run on this architecture.
=> bytesconv: add appropriate build tags for s390x

bytesconv.go
The `<` is occurs more frequently in the HTML string.
> Move `<`
```
name                 old time/op  new time/op  delta
AppendHTMLEscape-16  99.3ns ± 1%  93.8ns ± 1%  -5.50%  (p=0.000 n=10+10)
```
And I am wondering maybe we could disable the fast path? Looks like it is not used in most cases.
>  Disable fast path
```
name                 old time/op  new time/op  delta
AppendHTMLEscape-16  99.3ns ± 1%  82.3ns ± 3%  -17.10%  (p=0.000 n=10+10)
```
=> Imporve AppendHTMLEscape fast path

args.go, client.go
a new  pipelineWork does not  need  type  assertion
=> reduce type assertion 

lbclient.go
addresses https://github.com/valyala/fasthttp/issues/504 and is a followup to https://github.com/valyala/fasthttp/pull/556, addressing the outstanding feedback.
Adds support for adding/removing clients from LBClient utilizing a mutex as well as a user-defined callback for determining which HostClients to be removed
=> support adding/removing clients from LBClient

http.go
resolve: https://github.com/valyala/fasthttp/issues/1265
=> add nil check of req.body and resp.body on ReleaseBody

fs.go
This PR aims to fix #1101 and improve the changes proposed by #1108 
List of changes:
* Handling and proper conversion from/to backslashes.
* `rootFS.Root` is now empty and `ServeFile` has the control to convert a relative path to absolute.
* Using `filepath.IsAbs` to detect if a path is absolute or relative.
Extras:
* Some minor code linting.
* Removed `panic`s and now an error is returned. Crashing an app because the underlying OS calls does not work as expected, is not good. Also the function that may panic, already returns an errors for other situations.
=> Added Windows support and removed some panics

fs.go, go.sum
Add an option to allow empty root in the fsHandler
this is necessary to restore the capabilities before the commit https://github.com/valyala/fasthttp/commit/c7576cc10cabfc9c993317a2d3f8355497bea156
and to allow further functionality to be docked from the outside which is not affected by setting the root dir afterwards
related to:
https://github.com/gofiber/fiber/pull/1882#issuecomment-1120832500
=> Add an option to allow empty root in the fsHandler

server.go
The PR simplifies and slightly improves performance of "Connection: close" header.
Please see commit comments
=> Optimize server connection close logic

brotli_test.go, fs.go, fs_test.go, header.go, header_test.go, http.go, http_test.go, server.go, server_test.go
The CE is not so often used for plain APIs responses and even not so often used for static files and on the fly compression.
But still it should be checked each time so instead of peek headers map it will be faster to check a field.
Also having a dedicated field getter and setter simplifies code.
=> Response.ContentEncoding(): store as field and avoid using Header.SetCanonical()

args.go, header.go, header_timing_test.go
=> header.go Referer() optimize

header.go, http.go, http_test.go
The new method returns a body and uncompress if it's gzipped.
For some reason I thought that the GetBody() will do the uncomression for me itself. And today I had a new client who sends me compressed requests. So I implemented the method but it should be in the library for simplicity. Also this allows to developers to see it in auto-completion list so they will check it and avoid the mistake that I made.
=> BodyDecoded() for request and responses

.gitignore, client.go
Add `ConnPoolStrategy` field to `fasthttp.Client`.
PTAL @erikdubbelboer
=> Add `ConnPoolStrategy` field to client

server.go
#1320 
consolidate Accept behavior in server.Serve(acceptConn).
=> Consolidate TCPKeepalive in server.Serve (#1320)

fs.go
I want to serve files on read-only Root with FS.Compress.
This may be one of solution, could you review it?
```go
fs := &fasthttp.FS {
Root: "/read-only/html",
Compress: true,
CompressRoot: "/tmp/compressed",
}
```
=> Introduce FS.CompressRoot

http.go, http_test.go
The `round2` function in `http.go` didn't check for overflow when converting a `uint32` value +1 to an `int`. As a result, it could return 0 for large values, and hence attempting to handle a large response could result in a panic:
```
panic: runtime error: slice bounds out of range [:2930135446] with capacity 0
goroutine 36966 [running]:
github.com/valyala/fasthttp.appendBodyFixedSize(0xa1a1f8?, {0xa49b78?, 0x0?, 0x0?}, 0xa49b78?)
/home/meta/go/pkg/mod/github.com/valyala/fasthttp@v1.38.0/http.go:2166 +0x214
github.com/valyala/fasthttp.readBody(0xa1a140?, 0xc0403869c0?, 0xc02ef77cd0?, {0xa49b78?, 0xc02ef77cd0?, 0x6918e5?})
/home/meta/go/pkg/mod/github.com/valyala/fasthttp@v1.38.0/http.go:2085 +0x5d
github.com/valyala/fasthttp.(*Response).ReadBody(0xc00060ab60, 0xc0403869c0?, 0x0?) …
```
=> Prevent overflow and panic on large HTTP responses

args_test.go, client.go, client_test.go, client_timing_test.go, header.go, header_test.go, server_test.go
Don't run requests in a separate Goroutine anymore. Instead use proper
conn deadlines to enforce timeouts.
- Also contains some linting fixes.
=> Improve Client timeout

fasthttpadaptor/adaptor.go
This PR improves the performance of `fasthttpadaptor` by reducing the overhead of slice growth.
The current adapter records all written body in a byte slice, which causes horrible overhead when the body is bigger than a few kilobytes. However, this is unnecessary as we can just pass the response writer of fasthttp.
https://github.com/valyala/fasthttp/blob/ea6052464e7221956dedf9b9a523f8f9892c3d3b/fasthttpadaptor/adaptor.go#L108-L111
I compared the performance by modifying the `ServerGet` tests with **32 KiB responses**.
The original `ServerGet` _without the adaptor_:
```
BenchmarkServerGet1ReqPerConn-4                          4658205              2622 ns/op               0 B/op          0 allocs/op
BenchmarkServerGet2ReqPerConn-4                          5202049              2466 ns/op …
```
=> Reduce slice growth in adaptor

fasthttpadaptor/request.go, fasthttpadaptor/request_test.go
I changed the code to prevent string allocation by using unsafe conversion.
I wrote a benchmark test against changes.
Before:
After unsafe conversion:
=> byte to string unsafe conversion in fasthttpadaptor ConvertRequest method

fasthttpadaptor/adaptor_test.go
- Merge `TestNewFastHTTPHandler` and  `TestContentType`
=> test: merge test in adaptor_test.go

args.go, bytesconv_table_gen.go, fasthttpadaptor/request_test.go, header.go, header_test.go
pr for https://github.com/valyala/fasthttp/issues/179
=> feat: add header.PeekAll

header.go, header_test.go
refer to  https://github.com/valyala/fasthttp/pull/1394#discussion_r1001335924
=> optimize: adjust the behavior of PeekAll based on VisitAll

http.go, http_test.go
https://github.com/valyala/fasthttp/pull/1022 only handle ContinueReadBody(), this pr handle ContinueReadBodyStream()
=> fix: ignore body should not set content-length of streaming 

header.go, http_test.go
1. the length of trailer key should > 0
2. fix http_test words typo
=> fix: the length of trailer key should > 0

args.go, header.go, header_test.go
pr for https://github.com/valyala/fasthttp/issues/1400
=> feat: add PeekKeys and PeekTrailerKeys

fs.go, fs_test.go, header.go, header_test.go
pr for https://github.com/valyala/fasthttp/issues/1312
- change `SetByteRange`, support multipart/byteranges
- change `bigFileReader` and `fsSmallFileReader` which only handle complete files
- add `smallRangeReader` and `bigRangeReader` which only handle range files
- change `byteRangeUpdater` interface to `byteRangeHandler` 
**test**
- change `TestFSByteRangeSingleThread`, add `bigFileReader` and `fsSmallFileReader` test of `read` and `WriteTo`
- add `TestFSMultiByteRangeConcurrent` and `TestFSMultiByteRangeSingleThread`
- change `TestParseByteMultiRangeSuccess` and `TestParseByteRangeError`
=> feat: support mulit/range

http.go, http_test.go
Fix towards issue #1408 
- Set the loop to continue instead of panic making room for next read
- Added test case for the same `TestRequestMultipartFormPipeEmptyFormField`
=> fix form empty field error when used with pipe

client_test.go, http.go
This functionally works the same as e.g. Client.DoTimeout(), but we can also use it for Client.DoRedirect(). There is no way as far as I can tell to set a timeout on a DoRedirect call, so this makes it possible.
=> Request.SetTimeout

args.go
Annotation is writed `Make sure nothing is nil`.
when dst slice cap is bigger than len, some argsKV elements is nil.
So fill empty slice in for loop and `Make sure nothing is nil`.
=> Make sure nothing is nil in tmp slice

server.go
=> Assert with *net.TCPConn instead of *net.TCPListener in acceptConn() for TCP sockets

client.go, fasthttputil/pipeconns.go, tcpdialer.go
=> Use time.Until(deadline) instead of -time.Since(deadline)

client.go, http.go
These cases could result in leaks of the pool when they return early, and the `DoDeadline()` forgot to call `releasePipelineWork()` when it's timed out waiting for the response.
=> Fix some potential pool leaks

client.go
Since the `workPool` is the member field of `pipelineConnClient`, there is no need to pass the `workPool` explicitly as the parameter every time calling `acquirePipelineWork()` and `releasePipelineWork()`.
=> Make acquirePipelineWork() and releasePipelineWork() the member functions of pipelineConnClient

server.go, server_test.go
pr for https://github.com/valyala/fasthttp/issues/1389
- add `ShutdownWithContext` function to support shutdown with timeout and timeout happen  after all listener already close.
=> feat: add ShutdownWithContext

client.go, client_test.go
Currently it has a minor bug when the default port is not added for IPv6 addreses.
Likely in practice it doesn't affect the system.
Anyway please accept the PR that improves a performance a little bit and also exposes the addMissingPort() so that we can use it our apps code (now I had to copy the func).
=> client.go fix addMissingPort()

fasthttputil/inmemory_listener.go, fasthttputil/inmemory_listener_test.go, fasthttputil/pipeconns.go, fasthttputil/pipeconns_test.go
I have a use case where I need the code using this `InmemoryListener` to access the simulated address of the connection endpoints.
This PR adds optional addresses to the `PipeConns` and `InmemoryListener`.
If the feature is not used, the code behaves like before.
Example:
```go
func main() {
ln := NewInmemoryListener()
listenerAddr := &net.TCPAddr{IP: net.IPv4(127, 0, 0, 1), Port: 12345}
ln.SetLocalAddr(listenerAddr)
go client(ln)
lc, err := ln.Accept()
if err != nil {
log.Fatalf("unexpected error: %v", err)
}
log.Println(lc.LocalAddr(), lc.RemoteAddr())
}
func client(ln *InmemoryListener) {
clientAddr := &net.TCPAddr{IP: net.IPv4(127, 0, 0, 2), Port: 65432}
c, err := ln.DialWithLocalAddr(clientAddr)
if err != nil {
log.Fatalf("unexpected error: %v", err)
}
log.Println(c.LocalAddr(), …
```
=> add optional simulated addresses to pipeconn and inmemorylistener

README.md, server.go
PR for https://github.com/valyala/fasthttp/issues/1219
=> doc: optimize the comment of the Request.Done method

server.go, server_test.go
Some gin or net/http services have a different formvalue  function when migrating to fasthttp.
it maybe causes some bugs.
net/http:
```
// FormValue returns the first value for the named component of the query.
// POST and PUT body parameters take precedence over URL query string values.
// FormValue calls ParseMultipartForm and ParseForm if necessary and ignores
// any errors returned by these functions.
// If key is not present, FormValue returns the empty string.
// To access multiple values of the same key, call ParseForm and
// then inspect Request.Form directly.
```
The user can customize a formvalue function to avoid this problem, but it would be better if the framework provided this switch.
=> feat: support custom formvalue function

http.go, server.go
pr for https://github.com/valyala/fasthttp/issues/1455
=> optimize: allow http head when use getonly

fasthttpadaptor/adaptor.go, fasthttpadaptor/request.go
Since the [adapter](fasthttpadaptor/request.go) hardcode `HTTP/1.1`:
```go
r.Proto = "HTTP/1.1"
r.ProtoMajor = 1
```
Maybe this is better?
```go
r.Proto = b2s(ctx.Request.Header.Protocol())
if r.Proto == "HTTP/2" {
r.ProtoMajor = 2
} else {
r.ProtoMajor = 1
}
```
With this change, compose  `fasthttp` and `grpc` together is possible.
Usage:
```go
// start server
ws := &fasthttp.Server{...}
http2.ConfigureServer(ws)
ws.ServeTLS(...)
// transform to grpc request
if bytes.Equal(ctx.Request.Header.ContentType(), grpcContentType) {
fh := fasthttpadaptor.NewFastHTTPHandler(a.Rpc)
fh(ctx)
return
}
```
=> fix adapter support http2

client.go
The cleaner may remove hostclient unexpectedly.
I find that client will start cleaner when the first hostclient created.
The cleaner will remove hostclient if there is no conn in the hostclient. And cleaner will start judge logic immediately. At the same time, hostclient will create conn. So if client get the connsLock before hostclient create conn, the hostclient will be removed.
It may cause resource leak.
=> fix: client may remove hostclient incorrectly

client.go, client_test.go, strings.go
The getClientName() checks if !NoDefaultUserAgentHeader then returns the Client.Name field. But it also saves it to atomic field clientName. This is not needed and logic can be simplified. Previously the clientName vas a byte slice that was copied from c.Name and cached. See 02e0722fb73c6237818b8e5af55957eb919a7334
Fix #1458
=> client.go Simplify default UA logic

server.go, server_test.go, strings.go
The serverName atomic.Value field is used as a cache. This is not needed and logic can be simplified. See related #1458
=> server.go Simplify default Server name logic

uri.go, uri_windows.go, uri_windows_test.go
old result:
```
uri_test.go:211: Unexpected path "/foofoofoofoofoofoo". Expected "/foo". requestURI="/../../../../../foo"
```
=> fix: modify normalizePath

go.mod, go.sum
github.com/klauspost/compress no longer supports 1.16 and 1.16 is not exists on Fasthttp workflows.
=> update `github.com/klauspost/compress`, drop 1.16

b2s_new.go
New function use unsafe.SliceData to get pointer of the argument 'b',  it does not need to check len(b) and use less instructions in ASM code.
Environment: go1.20.0 linux/amd64
(The go code)
```go
func b2s(b []byte) string {
if len(b) == 0 {
return ""
}
return unsafe.String(&b[0], len(b))
}
func b2sfast(b []byte) string {
return unsafe.String(unsafe.SliceData(b), len(b))
}
```
(In ASM)
```diff
<unlinkable>.b2s STEXT size=108 args=0x18 locals=0x8 funcid=0x0 align=0x0
0x0000 00000 (b2s_new.go:8)     TEXT    <unlinkable>.b2s(SB), ABIInternal, $8-24
0x0000 00000 (b2s_new.go:8)     CMPQ    SP, 16(R14)
0x0004 00004 (b2s_new.go:8)     PCDATA  $0, $-2
0x0004 00004 (b2s_new.go:8)     JLS     71
0x0006 00006 (b2s_new.go:8)     PCDATA  $0, $-1
0x0006 00006 (b2s_new.go:8)     SUBQ    $8, SP
0x000a …
```
=> optimized b2s function

args_test.go, client.go, examples/client/client.go, header.go, header_test.go, http_test.go, server.go, server_test.go, stackless/func_timing_test.go, uri_test.go
Changes:
- Exected -> Expected
- ealier -> earlier
- reponse -> response
- trimed -> trimmed
- resore -> restore
- unexected -> unexpected
=> Correct typos in comments and tests

fasthttpproxy/proxy_env.go
This PR fixes godoc comments in `proxy_env.go`.
=> Add missing fasthttp prefix in example usage

client.go, client_unix_test.go, http.go, server_test.go, tcpdialer.go, uri.go, uri_test.go
This PR makes stylistic changes in internal code. It renames unexported functions and variables to match the common Go style:
- cancel_ctx -> cancelCtx
- svrUrl -> srvUrl (should be `srv` from `server`, not `svr`)
- isHttps -> isHTTPS
- isHttp -> isHTTP
- isIp6 -> isIP6
- isIp6WithoutPort -> isIP6WithoutPort
See https://github.com/golang/go/wiki/CodeReviewComments#initialisms and https://go.dev/doc/effective_go#mixed-caps.
=> Rename unexported funcs, vars to match common Go

.github/workflows/lint.yml, args.go, args_test.go, client.go, cookie.go, fasthttpadaptor/adaptor_test.go, fasthttputil/inmemory_listener.go, fs.go, header.go, http.go, http_test.go, lbclient.go, nocopy.go, server.go, uri.go
This PR does the following:
- add additional linter run options in GitHub lint's workflow;
- remove unused `//nolint` comments;
- use [`golangci-lint-action`](https://github.com/golangci/golangci-lint-action) because it's shorted and caches data.
Options:
- `--verbose` for clear visibility of which set of linters is run;
- `--enable=gochecknoinits` enables `gochecknoinits` (the repo has one `init()` which already `nolint`ed);
- `--enable=nolintlint` enables linter that reports redundant `//nolint` comments.
`structcheck` linter is deprecated and automatically disabled by `golangci-lint`.
=> Refactor golangci-lint config and remove redundant nolints

README.md, SECURITY.md, compress.go, examples/fileserver/fileserver.go, expvarhandler/expvar.go, header_test.go, pprofhandler/pprof.go, server_test.go, uri.go
This PR updates links to point to the official Go website that was moved to https://go.dev.  All links to https://godoc.org/ and https://golang.org/ are still valid but redirect to the new sites. It's preferred to use new ones.
Changes:
- Replace https://godoc.org with https://pkg.go.dev.
- Replace https://golang.org with https://go.dev.
- Replace https://golang.org/pkg with https://pkg.go.dev.
- Replace https://blog.golang.org with https://go.dev/blog.
- Use https://pkg.go.dev/golang.org/x/net/http2  instead of non-existing https://http2.golang.org/.
- Remove trailing slashes.
=> docs: replace links to old golang.org with new go.dev

client.go, client_example_test.go, compress.go, fasthttpadaptor/request.go, fasthttpproxy/proxy_env.go, fs.go, fs_test.go, header.go, http.go, lbclient.go, server.go, timer.go
This PR fixes only comments.
Changes:
- remove duplicated words;
- `its` writes without apostrophe;
- correct typos;
- `Github` -> `GitHub`, `MacOS` -> `macOS`.
=> docs: fix grammar issues and typos in comments

server.go
This PR adds `// Deprecated:` to the `ErrAlreadyServing` because this error is never returning from the `Serve`. The behavior changed in #731.
We can't just delete exported error to not break compatibility.
IDE understands this syntax and highlighted appropriately:
=> docs: deprecate ErrAlreadyServing as never returning

.github/workflows/lint.yml, fasthttputil/inmemory_listener_test.go, header_test.go
This PR fixes missing calls to `Response.Body.Close()` in tests. Also, enable `bodyclose` linter that detects such issues.
=> test: close response body

prefork/prefork_test.go
Without this change modal window appears when running `prefork_test.go` in Windows:
<a href="https://user-images.githubusercontent.com/3228886/218971204-5d36dfbc-3a44-4743-88ca-8d693a1fb335.png"><img src="https://user-images.githubusercontent.com/3228886/218971204-5d36dfbc-3a44-4743-88ca-8d693a1fb335.png"  height="300" ></a>
=> test: bind to localhost instead of all interfaces

http.go
This PR adds a call to close form file in `WriteMultipartForm` when copy error occured.
The line below shows that we need to call `fh.Close()`:
```go
if err = fh.Close(); err != nil {
return fmt.Errorf("cannot close form file %q (%q): %w", k, fv.Filename, err)
} 
```
=> http.go: close form file if copyZeroAlloc fails

client.go, client_test.go
I found this while developing unit tests for my application.
If we call DoDeadline without first checking that the deadline has expired, then we don't get the expected behavior of returning ErrTimeout.
The implementation (c *pipelineConnClient) of DoDeadline already contains the necessary check
```
if req.timeout < 0 {
return ErrTimeout
}
```
I also added it for
- Client
- HostClient
=> Immediately return ErrTimeout if deadline is already reached.

server_test.go
Simplify tests: use `fmt.Fprintf(...)` instead of `Write([]byte(fmt.Sprintf(...)))`
=> test: use Fprintf to simplify writing headers

header_test.go, server.go, server_test.go
Just reading the code found these typos.
=> test: fix typos in function, error message, comment

client.go, client_test.go
This PR fixes a situation when the second call to `client.Do` hangs when  using`c.ConfigureClient(hc)` on the first call `client.Do`.
Without the fix, `TestClientConfigureClientFailed` get stuck because mutex `c.mLock` is never unlocked. And timed out with the stack trace:
```
go test -timeout 30s -run ^TestClientConfigureClientFailed$ github.com/valyala/fasthttp -count=1 -v -race
=== RUN   TestClientConfigureClientFailed
=== PAUSE TestClientConfigureClientFailed
=== CONT  TestClientConfigureClientFailed
panic: test timed out after 30s
running tests:
TestClientConfigureClientFailed (30s)
goroutine 33 [running]:
testing.(*M).startAlarm.func1()
/usr/local/Cellar/go/1.20.1/libexec/src/testing/testing.go:2241 +0x219
created by time.goFunc …
```
=> client: fix Do hangs when configure host client fails

client.go, client_test.go
The PR fixes the situation when on `ErrConnPoolStrategyNotImpl` error `HostClient.Do()` hangs out.
This error is unlikely to happen in real life but for the sake of completeness I added `c.connLock.Unlock()` and the test.
=> client: fix HostClient.Do hangs on ErrConnPoolStrategyNotImpl

fasthttpadaptor/request.go
Without a dot the [comment](https://pkg.go.dev/github.com/valyala/fasthttp/fasthttpadaptor#ConvertRequest) looks as:
=> docs: add missing dot to ConvertRequest comment

.github/workflows/lint.yml, .github/workflows/test.yml
https://github.com/actions/setup-go/releases/tag/v4.0.0 enables cache by default.
=> GitHub actions/setup-go@v4

brotli.go, bytesconv.go, client.go, compress.go, fs.go, http.go, lbclient.go, peripconn.go, peripconn_test.go, server.go, stackless/func.go, timer.go, workerpool.go
Addresses #1522 and #1504. The latter is not fixed, but only referenced as the underlying double-close is not resolved.
Fixes: #1522
=> get rid of some panics

args.go
the same effect can be achieved if  the  destination slice do not  be reset  in `func (a *Args) CopyTo(dst *Args)` .
=> chore:remove redundant code

http.go, http_test.go
In release [v1.32.0](https://github.com/valyala/fasthttp/releases/tag/v1.32.0), there was a backwards incompatible change introduced as a (seemingly unintended) side-effect of [adding trailer support](https://github.com/valyala/fasthttp/pull/1165/commits/b2a0c32465dba2c024d127552733c9d10effa2b6).
The relevant scenario is in the case of a chunk-encoded request containing only a terminating chunk as its body payload (`0/r/n/r/n`). Previously, the[ content length would be set to the length of the body](https://github.com/valyala/fasthttp/pull/1165/commits/b2a0c32465dba2c024d127552733c9d10effa2b6#diff-6971e2713fe98b79ea18e9748bf68928f6ebcd4d93e7a27f10e7472ce6d78a48L1154) (0, in this case) whereas afterwards it [stopped doing that for chunked …
=> Fixed transfer-encoding for empty chunked payload

client.go
As discussed in #1529 , the main problem with the timeout failure is that req.timeout is not passed to dial to pause the dialing in time. One solution is to create a temporary dial. In order not to affect the original dial of HostClient, I choose to add the dialTimeout parameter in the dialHostHard function to control the dialing time. It will fail if HostClient.dial has been set, but general users should not set dial. In fact, I think the most appropriate solution is to make HostClient have a Dialer with a timeout attribute so that timeout can be set separately without affecting other settings and use HostClient.Dialer.dial instead of HostClient.dial, but obviously this will change a lot of code.
=> Fix issue #1529 : DoTimeout timeout failure

examples/client/client.go
- Use *errors.Is*  for to compare errors
- Reducing the level of nesting for easier code perception ( using switch and removing some else)
=> Refactor client's example code

http_test.go
This PR does the following refactorings in tests:
- use `strings.ReplaceAll(...) instead of strings.Replace(..., -1)`;
- remove `else`.
=> test: use strings.ReplaceAll, remove unnecessary else

pprofhandler/pprof.go
This PR replaces `strings.HasPrefix` with `bytes.HasPrefix` for consistency. Also, use `switch` instead of `if-else` chain.
=> pprofhandler: use bytes.HasPrefix for consistency

examples/client/client.go
This PR fixes `httpConnError` function (a mistake was made during refactoring #1539).
=> examples/client: fix copy-paste mistake

brotli_test.go, examples/multidomain/multidomain.go, http_test.go, server_test.go
This PR refactors tests and examples to use `ctx.WriteString(...)` instead of `ctx.Write([]byte(...))`. Also, use `ctx.WriteString("...")` instead of `io.WriteString(ctx, "...")` for consistency.
=> test: refactor to use WriteString

args.go, streaming.go
This PR does minor refactoring by dropping unnecessary `else` blocks.
=> Refactor by removing unnecessary else block

client.go, client_test.go
fix client http SetReadDeadline/SetWriteDeadline Deadline is reused
=> Request timeout settings for the same domain name are reused

fs.go
Previously, when creating multiple FS instances with a non-empty "CompressedFileSuffix" field concurrently, a data race on the global "FSCompressedFileSuffixes" might occur.
This was found in fiber, probably the largest web framework based on fasthttp:
git clone https://github.com/gofiber/fiber.git && cd fiber
git checkout 182f9f09705eab40c61a618835d46faee79c1e49
go test -v -race -run Test_App_Static_Prefix_*
=== RUN   Test_App_Static_Prefix_Wildcard
=== PAUSE Test_App_Static_Prefix_Wildcard
=== RUN   Test_App_Static_Prefix
=== PAUSE Test_App_Static_Prefix
=== CONT  Test_App_Static_Prefix
=== CONT  Test_App_Static_Prefix_Wildcard
==================
WARNING: DATA RACE
Write at 0x00c0001b1c50 by goroutine 7:
runtime.mapassign_faststr() …
=> fs: fix race condition on global map

header.go, header_test.go
This is a PR is response to #1572 
Thanks for your quick response, and for your work in maintaining this package overall. Here is a PR to entirely disable fasthttp setting special headers for you. This way the user has complete control over headers and the burden is on them to make sure things work correctly.
Feedback is welcome
=> add DisableSpecialHeaders option

.github/workflows/lint.yml, args_test.go, bytesconv.go, bytesconv_table_gen.go, client_timing_wait_test.go, cookie.go, fasthttpproxy/proxy_env.go, fasthttputil/pipeconns.go, fs_test.go, header_test.go, header_timing_test.go, http.go, http_test.go, prefork/prefork_test.go, server.go, server_test.go, tcpdialer.go, uri.go, uri_test.go, userdata_test.go
This PR:
- Formats all code with the command [`gofumpt -w .`](https://github.com/mvdan/gofumpt) (removed empty lines, replaces `var a =` with `a :=`, `}` indentation, octal literals etc.)
- Enables `gofumpt` linter in golangci-lint args to ensure everyone will follow the consistent style in future PRs;
- Removes `gofmt` because it's rules are a subset of `gofumpt`.
=> Enable gofumpt linter; format code `gofumpt -w .`

header.go, header_test.go, http.go, server_test.go, strings.go
Add config `SetAddVaryHeaderForCompression` to enable 'Vary: Accept-Encoding' header when compression is used.
Added a config variable `addVaryHeaderForCompress` to control this feature, with setter `SetAddVaryHeaderForCompression`.
To remain backward compatible, it's false by default.
When enabled, 'Vary: Accept-Encoding' header will be added when compression is used.
fix #1583
=> Auto add 'Vary' header after compression

fasthttpproxy/http.go
It's ok for fasthttpproxy use ipv6
=> fasthttpproxy support ipv6

client.go, client_test.go
=> Abstracts the RoundTripper interface and provides a default implement

http_test.go, round2_32.go, round2_32_test.go, round2_64_test.go
There was a missing import in `round2_32.go`.
I split the tests into per int size files too, since `unsafe.Sizeof(int(0)) == 4` runtime does not allow to pass 64 bit constants to 32 bit functions at compile time. Not sure if there is a better solution.
=> fix round2_32

.github/workflows/lint.yml, args.go, bytesconv_test.go, client.go, client_test.go, header.go, header_test.go, http.go, server.go, uri.go, userdata.go
This PR enables `gocritic` linter and fixes the following lint issues:
```
args.go:555:2: ifElseChain: rewrite if-else to switch statement (gocritic)
if idxPercent == -1 {
^
args.go:570:3: ifElseChain: rewrite if-else to switch statement (gocritic)
if c == '%' {
^
client.go:1346:34: unslice: could simplify req.Header.userAgent[:] to req.Header.userAgent (gocritic)
req.Header.userAgent = append(req.Header.userAgent[:], userAgent...)
^
client.go:2306:34: unslice: could simplify req.Header.userAgent[:] to req.Header.userAgent (gocritic)
req.Header.userAgent = append(req.Header.userAgent[:], userAgent...)
^
client.go:2413:34: unslice: could simplify req.Header.userAgent[:] to req.Header.userAgent (gocritic)
req.Header.userAgent = append(req.Header.userAgent[:], userAgent...)
^ …
```
=> Enable gocritic linter; fix lint issues

client.go, fs_test.go, header_test.go, http_test.go, server.go, server_example_test.go, server_test.go
This PR fixes spelling mistakes.
=> docs: fix typos in comments and tests

fasthttpproxy/proxy_env.go
This PR fixes package name in comments for the functions `fasthttpproxy.FasthttpProxyHTTPDialer` and `fasthttpproxy.FasthttpProxyHTTPDialerTimeout`
=> docs: fix package name in doc examples

client.go, http.go
We do use fasthttp for our project as a proxy between an uplink connection and a target. We discovered the following scenario where we run into an issue that we can't solve without a minor change to the fasthttp client.
The scenario that we have is the following:
From the upsteam connection we get a request which is replied with a steam of data from the target. All works fine using fasthttp and the customStream body. We simply copy from the target reader to the upstream writer. Now the upstream suddenly closes the TCP connection and we get an error while trying to copy our data from the target.
Now we definitelly want to close the still open connection to the target. The only thing we can do from within the handler is set `fastRequest.SetConnectionClose()` and …
=> Allow connection close for custom streams

fs_test.go
Because `path.Join` is for URL paths, and `filepath.Join` is for file paths.
=> Replace path.Join with filepath.Join in tests

server.go
Currently, the way `fasthttp.hijackConn` behaves is different from what can be expected with the `net.Conn` interface.
Normally, when you close a `net.Conn`, if you try to read or write again, you get errors.
But with `fasthttp.hijackConn`, when you close it, it gets cleaned and put back in the pool. If you try to read from or write to it again, it can cause two problems:
1. If it hasn't been reused yet, it might cause **null reference exception** because the underlying connection is `nil`.
2. If it has been reused, you might end up reading from or writing to a completely different connection, which is very bad.
I suggest not reusing `hijackConn` when `KeepHijackedConns` is enabled (it still will be reused when this option is disabled). This might make things a bit slower, but it will …
=> Make `hijackConn` behaviour compliant with `net.Conn` interface

client.go
If `HostClient` has `DialDualStack=true` and there is no custom `Dial` method specified, the `DialDualStack` setting will not work when sending requests using `DoDeadline` or `DoTimeout`. 
This issue was introduced in [ this commit ](https://github.com/valyala/fasthttp/commit/87cb886157ae414e178fd5bc14a57d5e1c8fcadb)
=> BUGFIX: HostClient.DialDualStack not work when using DoDeadline

client.go, client_test.go, http.go
Fix #1637 
Propagates the `DisablePathNormalizing` setting on a request URI to the redirect URI. This fixes an issue where redirect URIs were being normalized regardless of the setting on the request URI. This could effectively break the redirect URI, depending on the expectations of the server.
Preserves the current default behavior, which is for `DisablePathNormalizing` to be `false`.
=> Allow redirect URI path to not be normalized.

compress.go, fs.go, fs_fs_test.go
this is the following patch
https://patch-diff.githubusercontent.com/raw/valyala/fasthttp/pull/1374.patch
from pr #1374 
however with smaller differences, lets continue this development?
should fix #974
=> Add support to fs.fs on serve static files

client_timing_test.go
this will prevent  panics on benchmarks at client_timing_test.go
fixes #1641
=> fix benchmark panics on client_timing_test.go

.github/workflows/test.yml
add go 1.21.x into matrix go-version
how about drop support of go 1.17.x ?
=> add support to go 1.21.x into test.yml

allocation_test.go, b2s_new.go, b2s_old.go, bytesconv_32.go, bytesconv_32_test.go, bytesconv_64.go, bytesconv_64_test.go, bytesconv_table_gen.go, client_unix_test.go, fasthttpadaptor/b2s_new.go, fasthttpadaptor/b2s_old.go, fuzzit/cookie/cookie_fuzz.go, fuzzit/request/request_fuzz.go, fuzzit/response/response_fuzz.go, fuzzit/url/url_fuzz.go, reuseport/reuseport.go, round2_32.go, round2_32_test.go, round2_64.go, round2_64_test.go, s2b_new.go, s2b_old.go, tcp.go, tcp_windows.go, uri_unix.go, uri_windows.go, uri_windows_test.go
This PR removes outdated `// +build` constraints (it was replaced by `//go:build` in Go 16) by running `go fix ./...`.
We can remove OS-specific build constraints like `//go:build windows` if a file name ends with `_windows.go` (according to the [doc](https://pkg.go.dev/cmd/go#hdr-Build_constraints)).
=> chore: Remove redundant and outdated build constraints

.github/workflows/lint.yml, .golangci.yml
This PR adds [.golangci.yml](https://golangci-lint.run/usage/configuration/#config-file) with configuration for `golangci-lint`. The config file allows better flexibility in configuration in comparison with command-line parameters. E.g., in future, we might add additional helpful linters, disable some linter rules only for tests, etc.
Also, in the PR updated the version of golangci-lint to the latest currently [released](https://github.com/golangci/golangci-lint/releases/tag/v1.55.2).
=> chore: add golangci-lint config file for flexibility

brotli.go, compress.go, stackless/writer.go
- I noticed that fasthttp was taking up 1.8MB of heap memory, even though it wasn't being used. This turned out to be the stackless function: 1.80MB  github.com/valyala/fasthttp/stackless.NewFunc
- Lazy load the stackless functions with sync.Once, given this a simple atomic read, it shouldn't affect performance for the fast-path (I haven't seen benchmarks with compression enabled).
=> Lazy load stackless functions

.golangci.yml, bytesconv_test.go, client.go, fs.go, http_test.go
```sh
bytesconv_test.go:40:18: unnecessary conversion (unconvert)
expect := string(html.EscapeString(string(allcases)))
^
fs.go:873:28: unnecessary conversion (unconvert)
ff, ok := fileCache[string(path)]
^
fs.go:1597:16: unnecessary conversion (unconvert)
r := io.Reader(f)
^
client.go:1479:3: Duplicate words (d2) found (dupword)
//  0(not set)            d2            d2
^
client.go:1481:3: Duplicate words (d2) found (dupword)
//  0(not set)            d2            d2
^
http_test.go:3025:9: Duplicate words (size) found (dupword)
t.Run("limit response body size size", func(t *testing.T) {
^
```
=> Enable dupword, unconvert linters

.golangci.yml, args.go, server.go, server_test.go, streaming_test.go, tcpdialer.go, workerpool.go
This PR enables `wastedassign` and `whitespace` linters. And fixes the following issues:
```sh
server.go:2294: unnecessary leading newline (whitespace)
if ctx.Request.MayContinue() {
tcpdialer.go:378: unnecessary trailing newline (whitespace)
}
server_test.go:1922: unnecessary leading newline (whitespace)
for i := 0; i < 25; i++ {
args.go:554:2: assigned to idx, but reassigned without using the value (wastedassign)
idx := 0
^
server.go:1849:3: assigned to c, but reassigned without using the value (wastedassign)
c = nil
^
server.go:2587:2: assigned to ctx, but reassigned without using the value (wastedassign)
ctx = nil
^
workerpool.go:113:8: assigned to mid, but reassigned without using the value (wastedassign)
l, r, mid := 0, n-1, 0
^
workerpool.go:241:3: assigned to …
```
=> Enable wastedassign, whitespace linters; fix issues

http.go
These are the same statements at the beginning of io.CopyBuffer, but by doing them ourselves first we trade off a little cpu for not holding the 4kb buffer during the write.
=> copyZeroAlloc: Try WriteTo and ReadFrom before acquiring a buffer

.golangci.yml, client.go, fs.go, server.go, tcpdialer.go
This PR enables `lll` linter with `130` characters line length limit. And fixes up long lines exceeding the limit.
=> chore: Set max line length to 130 characters

.golangci.yml, args.go, client.go, client_test.go, client_unix_test.go, cookie.go, fs.go, fs_fs_test.go, fs_handler_example_test.go, header.go, header_timing_test.go, headers.go, http.go, lbclient.go, prefork/prefork.go, server.go, server_test.go, uri.go
This PR adds missing dots at the end of comments. Also, enables `godot` linter to ensure comments always end with a full stop. Additionally, enables `stylecheck` issue to ensure comments always start with a function name.
The full log of running `golangci-lint`:
```sh
prefork/prefork.go:78:59: Comment should end in a period (godot)
// IsChild checks if the current thread/process is a child
^
prefork/prefork.go:89:65: Comment should end in a period (godot)
// New wraps the fasthttp server to run with preforked processes
^
prefork/prefork.go:233:63: Comment should end in a period (godot)
// ListenAndServe serves HTTP requests from the given TCP addr
^
args.go:121:40: Comment should end in a period (godot)
// For example args.Sort(bytes.Compare)
^
args.go:232:40: Comment …
```
=> docs: Add missing dots at the end of comments

header.go, header_test.go, header_timing_test.go
The implementation is based on RFC-9110 5.6.6.
https://www.rfc-editor.org/rfc/rfc9110#name-parameters
The primary use case for parsing header parameters is for content negotiation, including multipart type boundaries.
The functor passed to VisitHeaderParams has a bool return value to allow the user to stop processing parameters early.
Examples of this being useful are to find a specific parameter, stop parsing after the q value, or to put a hard limit on the number of parameters a client can include.
I had originally written this for a different project using fasthttp, but I figured it was generic enough that it may warrant being merged in for others to use as well.  If not, no feelings will be hurt.
The implementation of validHeaderFieldByte is a little silly looking, but it's as fast as …
=> feat: add function to parse HTTP header parameters

.golangci.yml, client.go, expvarhandler/expvar.go, fs.go, header_test.go, http.go, http_test.go, server.go
This PR refactors code by changing `if len(str) == 0 {` to more idiomatic `if str == "" {`. Additionally, enables gocritic's `emptyStringTest` check to prevent such code in the future.
See ["Empty string check"](https://dmitri.shuralyov.com/idiomatic-go#empty-string-check).
=> Change empty string checks to be more idiomatic

tcpdialer.go
Sometimes, users do not need to use DNS resolution because they have already determined that the requested address is a list of IP addresses.
=> add DisableDNSResolution for TCPDialer. 

server.go, server_test.go
Closes #1568 
- Add `rejectedRequestsCount` field
- Increment `rejectedRequestsCount` when connection is rejected
- Implement `GetRejectedConnectionsCount` function that returns `rejectedRequestCount`
- Write test
=> Implement `GetRejectedConnectionsCount` function

.github/dependabot.yml, .github/workflows/cifuzz.yml, .github/workflows/lint.yml, .github/workflows/security.yml, .github/workflows/test.yml
- Add dependabot to track `github-actions` and `go` dependencies
- Add go1.22 to test matrix
- Update all outdated github actions
go 1.22 was released today: https://go.dev/blog/go1.22
=> Updates to GitHub Actions, add go1.22 to Test Matrix

header.go, header_test.go, http_test.go, strings.go
Require that HTTP versions match the following pattern: HTTP/[0-9]\.[0-9]
Fix: https://github.com/valyala/fasthttp/issues/1703
=> Follow RFCs 7230 and 9112 for HTTP versions

header.go, header_test.go
Prevent request smuggling when fasthttp is behind a reverse proxy that might interprets headers differently by being stricter. Should also prevent request smuggling when fasthttp is used as the reverse proxy.
=> Prevent request smuggling

fasthttpadaptor/adaptor.go, fasthttpadaptor/adaptor_test.go
this change properly add the adaptor ResponseWriter the capability of Hijacker.
and so it will address issues (#946 and #87) , and maybe others I am not aware of
=> adaptor ResponseWriter - adding Hijack method and pass proper fields 

s2b_new.go, s2b_old.go
This PR reverts changes from #1695 because they are unnecessary.
According to the [Go documentation on Build Constraints](https://pkg.go.dev/cmd/go#hdr-Build_constraints), the constraint `go1.20` applies to `go1.20`, `go1.21`, `go1.22`, and so on. Conversely, `!go1.20` applies to `go1.18` and `go1.19`.
Here's the relevant excerpt from the documentation:
> During a particular build, the following build tags are satisfied:
> ...
> - a term for each Go major release, through the current version: "go1.1" from Go version 1.1 onward, "go1.12" from Go 1.12, and so on.
Currently, `fasthttp` supports the following Go versions: `1.18`, `1.19`, `1.20`, `1.21`, `1.22`.
With build tags, we should ensure that:
-  `s2b_new.go` is included only when building with Go `1.20`, `1.21`, `1.22`;
- `s2b_old.go` …
=> Remove unnecessary build tag go1.21

.github/workflows/lint.yml, .golangci.yml, args_test.go, brotli_test.go, bytesconv.go, client_test.go, fasthttpadaptor/adaptor_test.go, fs.go, fs_fs_test.go, fs_test.go, fuzz_test.go, header_test.go, http.go, http_test.go, prefork/prefork.go, server_test.go
The PR upgrades golangci-lint version to the latest [v1.56.2](https://github.com/golangci/golangci-lint/compare/v1.55.2...v1.56.2)), enables a lot of gocritic's checks and fixes up issues.
- in idiomatic Go, we should use `len(v) =! 0` instead of `string(v) != ""` when `v` is `[]byte`. See https://dmitri.shuralyov.com/idiomatic-go#empty-string-check;
- we should use `v != ""` instead of `len(v) != ` when `v` is string;
- we can compare byte slices with `bytes.Equal` instead of converting them to string;
- `rw.Write([]byte(str),...` can be rewritten to `rw.WriteString(str,...`.
```sh
prefork/prefork.go:155:14: evalOrder: may want to evaluate cmd.Start() before the return statement (gocritic)
return cmd, cmd.Start()
^
bytesconv.go:38:6: emptyStringTest: replace `len(sub) …
```
=> Upgrade golangci-lint to v1.56.2; fix gocritic issues

.golangci.yml, client_timing_test.go, fs.go, header.go, http.go, http_test.go, prefork/prefork.go, server.go, status.go, userdata.go
The PR enables temporarily disabled `httpNoBody`, `initClause`, `paramTypeCombine`, `typeUnparen` checks from [gocritic](https://go-critic.com/overview.html) linter and fixes up lint issues.
```
fs.go:1353:1: paramTypeCombine: func(filePath string, fileEncoding string) (*fsFile, error) could be replaced with func(filePath, fileEncoding string) (*fsFile, error) (gocritic)
func (h *fsHandler) compressAndOpenFSFile(filePath string, fileEncoding string) (*fsFile, error) {
^
fs.go:1535:1: paramTypeCombine: func(filePath string, fileEncoding string) (*fsFile, error) could be replaced with func(filePath, fileEncoding string) (*fsFile, error) (gocritic)
func (h *fsHandler) newCompressedFSFile(filePath string, fileEncoding string) (*fsFile, error) {
^
header.go:1433:1: …
```
=> Enable several gocritic checks; resolve identified issues

args_test.go, header_test.go, http_test.go, uri_test.go
This PR refactors the tests for `noCopy` structs, eliminating the need for `//nolint:govet` comments.
`govet` raises lint issues in tests on the `reflect.DeepEqual(h1, h2)` line where `h1, h2` are of type `Header`. This is because `Header` contains the special field `noCopy`, which triggers `govet`. To appease `govet`, we can pass pointers to `reflect.DeepEqual(&h1, &h2)`. According to the [documentation](https://pkg.go.dev/reflect#DeepEqual), we can do this without breaking tests because "Pointer values are deeply equal if they are equal using Go's == operator or if they point to deeply equal values."
=> test: remove `//nolint:govet` comments

.golangci.yml, bytesconv_test.go, client_test.go, compress_test.go, header.go, header_test.go, http.go, stackless/func_test.go, stream_test.go
The PR enables the [`perfsprint`](https://golangci-lint.run/usage/linters/#perfsprint) linter in the golangci-lint configuration file. The `fasthttp` library is  heavily focused on performance, making this linter a beneficial addition.
This PR fixes up the lint issues that arose from `persprint`. All of these were minor:
- replace `fmt.Errorf("msg")` with `errors.New("msg))`;
- replace `fmt.Sprintf("%d", n)` with `strconv.Itoa(n)` in tests.
=> Enable perfsprint linter; fix up lint issues

fs.go, http.go, server.go
The PR improves code by renaming the error variables to more meaningful names:
- `err1` -> `errf` (error during flush);
- `err2` -> `errc` (error during close);
- `err1` -> `errw` (error during write).
=> refactor: rename error local variables

.golangci.yml, server_test.go
This PR simplifies `err == nil || err != nil && !strings.EqualFold(err.Error(), "timeout")` statement. If the first `err` is non-`nil` then the second `err` is automatically `non-nil`.
The redundancy is found by `govet`'s `nilness` check:
```sh
❯ ./bin/golangci-lint run
server_test.go:4149:24: nilness: tautological condition: non-nil != nil (govet)
if err == nil || err != nil && !strings.EqualFold(err.Error(), "timeout") {
^
server_test.go:4209:24: nilness: tautological condition: non-nil != nil (govet)
if err == nil || err != nil && !strings.EqualFold(err.Error(), "timeout") {
^
```
=> test: remove redundant error check

bytesconv.go, bytesconv_test.go
The PR addresses a panic issue in the `ParseIPv4` function when the length of the destination byte slice exceeds 4.
The test case that checks for this issue is `testParseIPv4(t, net.IP{0, 0, 0, 0, 0}, "0.0.0.0", true)`:
```
=== RUN   TestParseIPv4
=== PAUSE TestParseIPv4
=== CONT  TestParseIPv4
--- FAIL: TestParseIPv4 (0.00s)
panic: BUG: dst must not be nil [recovered]
panic: BUG: dst must not be nil
```
In addition to the fix, this PR introduces several negative test cases to enhance the coverage of the `ParseIPv4` function:
- empty ipStr: `testParseIPv4(t, nil, "", false)`;
- invalid first octet: `testParseIPv4(t, nil, "b.1.2.3", false)`;
- invalid last octet: `testParseIPv4(t, nil, "1.2.3.b", false)` and `testParseIPv4(t, nil, "1.2.3.456", false)`.
=> fix: panic in ParseIPv4 when len(dst) > 4

client_test.go
The PR refactors client tests: return an error instead of using `t.Fatal` with `panic`. This is a more elegant and shorter solution.
=> test: remove panics in client tests

.github/workflows/test.yml
- Add `macos-14` platform which uses Apple M1 cpu's (ARM64).
- Add `-shuffle=on` to enable shuffling the unit-tests order. Each run will run tests in different order to catch tests depending on others or using data from other tests.
We recently enabled both of these options in gofiber with great success. https://github.com/gofiber/fiber/blob/main/.github/workflows/test.yml#L37
=> Add macos-14 platform, enable shuffle of unit-tests

http.go, server.go
The functions `brotliBody`, `gzipBody`, `deflateBody`, and `zstdBody` always return a `nil` error. Therefore, this PR removes `error` from the return argument of these functions.
=> refactor: do not return error as it is always nil

.github/workflows/test.yml, client.go, http.go, http_test.go
When using body streaming with keep-alive connections current version ignores write errors and returns broken connection to pool. Fix propagates write errors to bodyStream close function and closes connection if error occurs.
Fix #1743
=> fix: propagate body stream error to close function (#1743)

client.go
When using a url like http://example.com,/ URI will parse "example.com," as host. HostClient then splits this by "," into multiple addresses and will connect to example.com. HostClient splitting the address by "," is only for direct use, not for use with Client.
=> Don't allow , in host when using Client

fs.go, fs_fs_test.go
In current implementation of Fasthttp FS, GenerateIndexPages doesn't work properly with DirFS or embed.FS because of `fs.ValidPath` function. 
When you open `""` path using with DirFS it returns `invalid path error`. When using embed.FS, it returns `file does not exist` error. 
So, if the path is `""` both cases need to covered properly. 
**Note:** I ain't also sure this is a good solution.  Perhaps need smarter solution to cover more edge cases.
=> fs: fix GenerateIndexPages when DirFS or embed.FS is used

fs.go
openIndexFile overrides the index path to make it usable with subdirs. This causes wrong index path like `/index.html` when the dirPath is empty string.
=> fs: fix openIndexFile when dirPath is empty string

prefork/prefork.go, prefork/prefork_test.go
It's better to use an environment variable as they are more standard. They way flags are parsed isn't standardized within the Go ecosystem.
Fixes: https://github.com/valyala/fasthttp/issues/1782
=> Use FASTHTTP_PREFORK_CHILD env variable to detect child

prefork/prefork_test.go
The PR corrects one spelling mistake inside `Test_New`.
=> test: fix typo

fasthttpproxy/http.go, fasthttpproxy/proxy_env.go
fast http client may hang forever when reading from proxy connection. 
code to reproduce the bug:
proxy server
```
package main
import (
"log"
"net/http"
"time"
)
func main() {
handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
log.Printf("Received request %s %s %s\n", r.Method, r.Host, r.RemoteAddr)
if r.Method == http.MethodConnect {
time.Sleep(1 * time.Hour) // proxy server may hang a long time for some reason
}
})
log.Fatal(http.ListenAndServe(":8181", handler))
}
```
fast http client  hangs and ignores the timeout because proxy server doesn't response
```
package main
import (
"fmt"
"os"
"time"
"github.com/valyala/fasthttp"
"github.com/valyala/fasthttp/fasthttpproxy"
)
func main() {
client := fasthttp.Client{
ReadTimeout:  5 * time.Second,
WriteTimeout: 5 * …
```
=> fix:  add timeout to proxy connection reading and writing

client.go, cookie.go, fs.go, header.go, http.go, tcpdialer.go, workerpool.go
1. Reduce RequestHeader from **368** bytes to **360** bytes
2. Reduce Request from **816** bytes to **800** bytes
3. Reduce Response from **432** bytes to **416** bytes
4. Reduce Client from **312** bytes to **288** bytes
5. Reduce HostClient from **416** bytes to **392** bytes
6. Reduce PipelineClient from **176** bytes to **168** bytes
7. Reduce pipelineConnClient from **216** bytes to **208** bytes
8. Reduce Cookie from **232** bytes to **224** bytes
9. Reduce FS from **184** bytes to **160** bytes
10. Reduce fsHandler from **168** bytes to **160** bytes
11. Reduce ResponseHeader from **328** bytes to **320** bytes
12. Reduce headerScanner from **128** bytes to **120** bytes
13. Reduce TCPDialer from **104** bytes to **96** bytes
14. Reduce workerPool from **152** btyes to **144** …
=> Optimize struct field order to reduce memory usage

server.go
Fix possible race condition on request ctx done #1662
=> Fix possible race condition on request ctx done #1662

header.go, header_test.go
See issue #1808. When FastHTTP receives a header value suffixed or prefixed with tabs, they should be stripped.
=> Fix header parser (#1808)

bytesconv.go
- Replace custom implementation of `AppendUInt` with `strconv.AppendUint` as discussed in #1805
=> Replace custom AppendUint with strconv.AppendUint

brotli.go, client.go, client_test.go, client_timing_test.go, compress.go, cookie.go, examples/client/client.go, fasthttpadaptor/adaptor.go, fasthttputil/inmemory_listener.go, fasthttputil/inmemory_listener_test.go, fasthttputil/pipeconns.go, fs.go, fs_test.go, header.go, header_test.go, http.go, lbclient.go, peripconn.go, prefork/prefork.go, reuseport/reuseport.go, server.go, server_test.go, server_timing_test.go, stackless/writer.go, tcpdialer.go, uri.go, userdata_test.go, workerpool.go, zstd.go
@erikdubbelboer Not sure your thoughts on this since it changes the order of fields in some of the public structs.
Affected Public Structs:
- Client
- HostClient
- Cookie
- URI
- ErrDialWithUpstream
- TCPDialer
- RequestCtx
- Response
- Request
- Server
- Prefork
- LBClient 
This is something we ran into in Fiber https://github.com/gofiber/fiber/pull/3079, we had a lot of places in the code base using `positional` instead of `named` fields. This can cause major bugs in the future when the underlying struct changes. I wrote an analyzer to detect and fix these issues. After fixing those, I ran `betteralign` against the whole code base.
Summary of savings:
```
/fasthttp/fasthttputil/inmemory_listener.go:16:23: 16 bytes saved: struct with 40 pointer bytes could be 24 …
```
=> Use Named Fields and Align Structures to Reduce Memory Usage

http.go, server_test.go
The StreamRequestBody feature on the server side should not read content that does not belong to the current request body.This is more logical and consistent with the result of not using the StreamRequestBody feature.
Fixes: [#1816](https://github.com/valyala/fasthttp/issues/1816). 
The reason for addressing this issue is that the Read method of requestStream assumes it should only read up to the Content-Length number of bytes.
=> StreamRequestBody shouldn't read more data than actual need.

header.go, header_test.go, http.go
Replace the field `bufKV` whose size is **56** bytes in ResponseHeader and RequestHeader with two `[]byte` fields only **48** bytes.
+ Reduce ResponseHeader from **320** to **312** bytes.
+ Reduce RequestHeader from **360** to **352** bytes.
+ In the benchmark tests, although there is no significant performance improvement, it theoretically reduces memory usage by **2.2%** to **2.5%**.
=> Reduce the size of ResponseHeader and RequestHeader

client.go
The current implementation makes some incorrect assumptions about observing changes in the state of wantConn.
The following two pull requests failed the GitHub workflow named `test` due to the `TestHostClientMaxConnWaitTimeoutError` test case.
https://github.com/valyala/fasthttp/pull/1818
https://github.com/valyala/fasthttp/pull/1829
Of course, we don't need to guarantee that the return value of HostClient.connsWait.len() is zero when all client calls have exited, because this doesn't affect the correctness of the program in the same way as the HostClient.MaxConns field does. 
There is a test in the suite, TestHostClientMaxConnWaitTimeoutError, which can cause the test to fail under certain conditions. We either need to remove this test or find a way to fix it. Additionally, false waiters …
=> TestHostClientMaxConnWaitTimeoutError test case sometimes fails

fs.go, fs_test.go
Add a dedicated cache container for the zstd compression algorithm to prevent discrepancies between the response content and the implied Content-Encoding in certain scenarios.Fix: https://github.com/valyala/fasthttp/issues/1827#issue-2459271452
=> Add a dedicated cache container for the zstd compression algorithm

server.go
In the current implementation, there are several places where it's assumed that SetReadDeadline and similar functions logically won't affect a closed connection. However, these assumptions may not hold in certain specific situations. Therefore, instead of asserting that such errors will never occur, simply return the errors encountered during the execution of these methods.
The current implementation of ShutDown can, under certain conditions, invalidate these assumptions.
https://github.com/valyala/fasthttp/blob/d29a2b90a63494f2007471d0653d5d85ead61397/server.go#L1600-L1609
We cannot assume that when the program reaches this point, the connection state has not yet transitioned from StateNew to the actual StateIdle. Even if this transition takes 5 seconds, we cannot make assumptions about …
=> We cannot avoid continuing to call SetReadDeadline and similar methods after the connection is closed.

fasthttpproxy/dialer.go, fasthttpproxy/dialer_test.go, fasthttpproxy/http.go, fasthttpproxy/proxy_env.go, fasthttpproxy/socks5.go
https://github.com/valyala/fasthttp/issues/1822
In this issue, I noticed that the existing implementation doesn't leverage fasthttp's dialer mechanism, so I created this pull request.
At the same time, provide more comprehensive support for proxy environment variables and allow configuration of the fasthttp dialer.
No tests were committed, and the logic is built on top of the existing fasthttpproxy foundation. I noticed that the original fasthttpproxy also didn't include any test code.
The proxy address is not universal, but I did some local debugging and didn't find any issues.
=> Merge the various proxy dialer implementations from the fasthttpproxy into a single struct.

fs.go
For requests with paths that do not have a trailing slash, we always redirect to the corresponding path with a trailing slash. This approach avoids assuming that users will definitely be redirected to the trailing-slash path and instead ensures that we return a proper redirection, checking for an index file or generating a directory listing. We do this because we should not make assumptions about user behavior. Similarly, the cache for `dir/` requests should not be used for `dir` requests.
This issue is also reflected in this issue: https://github.com/valyala/fasthttp/issues/1839
```bash
~/GolandProjects/cbrotli_bug/fasthttp fasthttp_test_issue2 56s
❯ go test -race --count=2 .
--- FAIL: TestZstdBytesConcurrent (1.03s)
zstd_test.go:22: timeout
--- FAIL: TestZstdCompressConcurrent (1.02s) …
```
=> Fix Different request paths share the same `fs` cache is some cases.

server_test.go
Reduce the test duration to 36% of the original time.
Before Time Spend See Issue: https://github.com/valyala/fasthttp/issues/1839
After Commit:
```bash
~/GolandProjects/cbrotli_bug/fasthttp fasthttp_test_issue2*
❯ go test .
ok  	github.com/valyala/fasthttp	2.558s
~/GolandProjects/cbrotli_bug/fasthttp fasthttp_test_issue2*
❯ go test -count=2
PASS
ok  	github.com/valyala/fasthttp	4.976s
~/GolandProjects/cbrotli_bug/fasthttp fasthttp_test_issue2* 5s
❯ go test -count=3 .
ok  	github.com/valyala/fasthttp	7.389s
~/GolandProjects/cbrotli_bug/fasthttp fasthttp_test_issue2* 8s
❯ go test -count=4 .
ok  	github.com/valyala/fasthttp	9.991s
```
=> Make the tests complete earlier.

client_test.go
The `testClientDoTimeoutError` and `testClientGetTimeoutSuccess` test function does not immediately return or fatal when the test fails. Instead, it continues to stringify the byte slice that was passed as the `dst` parameter to the `Client.GetTimeout` method. If the test fails due to a timeout, the request may still be ongoing, and there might be a data race between writing to `dst` and the stringification operation.
Other test cases also continue to access the body after a request failure, but they are not related to timeouts. I believe this should not be an issue.
=> Fix potential data race reports when the `-race` flag is enabled.

client_test.go, server_test.go
In some cases, the goroutines started by one test do not terminate smoothly before the next round of tests begins, causing interference between tests.
Performance Impact: This results in test completion times not increasing linearly with the count value.
Correctness Impact: It affects the accuracy of memory allocation test cases.
Fix partial issues of this issue.: https://github.com/valyala/fasthttp/issues/1839
=> Fix issues with tests interfering with each other in certain situations.

server.go
For example, when using chunked encoding, it's possible that `br` has only read the request headers.Even br.Buffered() == 0.
=> When `StreamRequestBody` is set to `true`, we cannot safely release `br`

client.go, client_test.go
Another implementation of RetryIfErr
* Support for delayed retry logic
* Support for resetting the request timeout before retrying
* Users can decide whether to retry based on the request error and the number of retries.
Estimating the time required for a request to complete is relatively straightforward, but when retries are factored in, it becomes challenging to gauge this time accurately.
At the same time, comment out the logic for retrying non-idempotent requests：
```go
if !retry {
break
// Retry non-idempotent requests if the server closes
// the connection before sending the response.
//
// This case is possible if the server closes the idle
// keep-alive connection on timeout.
//
// Apache and nginx usually do this.
//
// This assertion cannot ensure that the server has not read …
```
=> RetryIf might need more information and greater control over the execution flow.

fasthttpadaptor/adaptor_test.go, fasthttpadaptor/request.go, header.go
Hi Developers,
This pull request fixes the improper memory reuse in NewFastHTTPHandler reported in this [issue](https://github.com/valyala/fasthttp/issues/1859).
If there are any further adjustments or improvements you'd like me to make, please don't hesitate to reach out :)
Best regards!
=> Fix improper memory reuse in NewFastHTTPHandler

server.go
Decrease the `ConnState.String()` runtime by **95%**.
We can replace the `map` with `[]string` like the code in [https://github.com/valyala/fasthttp/blob/65e989e8b8bcf2541d840fcf27dcf8a11931b9db/status.go#L85-L151](https://github.com/valyala/fasthttp/blob/65e989e8b8bcf2541d840fcf27dcf8a11931b9db/status.go#L85-L151)
```go
func BenchmarkStatusToString(b *testing.B) {
for i := 0; i < b.N; i++ {
StateNew.String()
StateActive.String()
StateIdle.String()
StateHijacked.String()
StateClosed.String()
}
}
```
```
goos: linux
goarch: amd64
pkg: github.com/valyala/fasthttp
cpu: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
│    old.txt    │           new.txt            │
│    sec/op     │    sec/op     vs base        │
StatusToString-8   18.9250n ± 0%   0.8873n ± 1%  -95.31% (n=50)
│  old.txt   │ …
```
=> Improve the performance of ConnState.String()

cookie.go
Replace the field `bufKV` with two `[]byte` fields and remove the filed `buf`.
- Reduce Cookie from **224** to **192** bytes.
- In the benchmark tests, although there is no significant performance improvement, it theoretically reduces memory usage by **14.3%**.
```diff
type Cookie struct {
-       buf    []byte    // -24 bytes
-       bufKV  argsKV    // -56 bytes
+       bufK   []byte    // +24 bytes
+       bufV   []byte    // +24 bytes
}
```
In the benchmark test, the execution time increased slightly by about 1%.
```
goos: linux
goarch: amd64
pkg: github.com/valyala/fasthttp
cpu: AMD EPYC 7763 64-Core Processor                
│   old.txt   │              new2.txt              │
│   sec/op    │   sec/op     vs base               │
CookieParseMin-4         26.55n ± 1%   26.53n ± 1% …
```
=> Reduce the size of the Cookie by 32 bytes.

peripconn.go
If using MaxConnsPerIP setting along with HTTPS (TLS) server, the connection accepting leads to panic because of wrong type assertion.
This pull request fixes that problem
=> fix: type assertion to perIPTLSConn instead of erroneous perIPConn

header.go
Hi Developers,
As described in [this issue](https://github.com/valyala/fasthttp/issues/1862), currently `header.Set` does not reset but adds cookies. This pull request attempts to fix this so that `header.Set resets` cookies instead of adding them.
Feel free to let me know if there are any further changes you would like me to make.
Best regards!
=> Add a note to clarify header.Set behavior on cookies

http.go, http_test.go
Implemented `GetRequestTimeout` func to get the timeout attribute of the request.
#1745
pd: is this what you guys had in mind?. I still need to document this btw.
=> feat (request): expose req timeout

uri.go
Improve the performance of `ishex` and `unhex` by reducing branching through table lookup.
=> improve ishex and unhex by hex2intTable

.github/workflows/lint.yml, .golangci.yml, client_test.go
The PR upgrades golangci-lint to the newest version [1.61.0](https://github.com/golangci/golangci-lint/releases/tag/v1.61.0).
Additionally, replaces `t.Errorf(err.Error())` with `t.Error(err)` as suggested by `govet`.
=> chore: Upgrade golangci-lint to 1.61.0

fasthttpproxy/http.go, fasthttpproxy/socks5.go
- Added `FasthttpHTTPDialerDualStack` to support dual-stack (IPv4 and IPv6) connections for HTTP proxies, enabling IPv6 proxy usage.
- Added `FasthttpSocksDialerDualStack` to support dual-stack (IPv4 and IPv6) connections for SOCKS5 proxies, enabling IPv6 proxy usage.
- Improved dialer configuration to ensure compatibility with both IPv4 and IPv6 proxies.
=> feat(fasthttpproxy): add dual-stack connection support to enable IPv6 proxies for HTTP and SOCKS5 dialers

server.go, server_test.go
In my opinion, the root cause of issue #1879 is that the `done` channel in `ctx.s` is nil. We can simply create `done` channel in `fakeServe`r during the initialization of RequestCtx.
Original
```
requestCtx.Init()
→ ctx.Init2
→ ctx.s = fakeServer        (the ctx.s.done is nil)
requestCtx.Err()
→ ctx.Done()        (generate the new buffered channel and send struct{}{} since the ctx.s.done is nil)
→ error is returned
```
Fix
```
requestCtx.Init()
→ ctx.Init2
→ ctx.s = fakeServer        (the ctx.s.done is initialized)
requestCtx.Err()
→ ctx.Done()        (return ctx.s.done since it is non nil)
→ error is nil
```
=> fix RequestCtx is canceled (#1879)

http.go, http_timing_test.go
Improve performance of `copyZeroAlloc` function
According to issue #1889 
> it looks like go's `io.CopyBuffer` always uses the `WriterTo` interface if it's available, much like `copyZeroAlloc`
> However, `File` and `TCPConn` unfortunately have a fallback in their `WriterTo` that calls `io.Copy` if sendfile isn't possible, which allocates an implicit buffer
zero-copy `sendfile` can only be triggered when copying between `os.File` and `net.TCPConn`. Since the function confirming zero-copy `sendfile` is a private function, we can use `ReadFrom` or `WriteTo` only in the specific scenario.
In the original `copyZeroAlloc` implementation, both `os.File` and `net.TCPConn` have a `WriteTo` method, so the function calls `WriteTo`. However, zero-copy in Go is enabled only when copying between …
=> perf: improve copyZeroAlloc for os.File and net.TCPConn

.golangci.yml, client.go, http.go, uri.go
The PR enables the rule `revive.indent-error-flow` and fix up lint issues.
=> refactor: fix revive.indent-error-flow lint issues

cookie.go, cookie_test.go
This PR fixes issue #1900 
According to [RFC6265](https://datatracker.ietf.org/doc/html/rfc6265#section-5.2.2), a max-age value of 0 or less is valid and is interpreted as forcing the cookie to expire immediately.
In the Go `net/http` package, they set `Max-Age` to `0` when the `cookie.MaxAge < 0`. 
Before the fix
|                    |       net/http           |        fasthttp           |
|--------------|----------------------|---------------------|
|maxAge = 0 | unset                      |         unset             |
|maxAge > 0 | Max-Age=maxAge | Max-Age=maxAge| 
|<mark>maxAge < 0</mark> | <mark>Max-Age=0</mark>            |         <mark>unset</mark>             |
After the fix
|                    |       net/http           |        fasthttp           | …
=> fix: incorrect handling of negative cookie.maxAge #1900

http.go
fasthttp allows newlines (\n) between the chunk size and the CRLF (i.e. in the chunk extension). This can cause request smuggling issues with some reverse proxies. This PR prevents this potential vulnerability by disallowing newlines in the chunk extension. 
I've also corrected two unescaped carriage returns in error messages which messed with the output formatting.
=> fix: lenient chunk extension parsing leading to request smuggling issues

header.go, header_test.go
Fixes #1909 
According to modern HTTP/1.1 specifications RFC 7230 `identity` as a value for `Transfer-Encoding` was removed in the errata to RFC 2616. See section "HTTP Transfer Coding Registry" in [https://www.iana.org/assignments/http-parameters/http-parameters.xhtml](https://www.iana.org/assignments/http-parameters/http-parameters.xhtml)
In this PR, I still follow the implementation in [net/http](https://cs.opensource.google/go/go/+/master:src/net/http/transfer.go;l=612;drc=fafd4477f3d19f2c11a628e6e407ecf9924309c1) to retain the logic for handling `Transfer-Encoding: identity`. However, `identity` will not be included in the output headers.
=> fix: "identity" has been deprecated #1909

fuzz_test.go, uri.go, uri_test.go
`http://google.com#@github.com` parses incorrectly as `github.com` instead of `google.com`.
Reported by Jesse Yang
=> Fix parsing of bad urls with #

README.md
This PR changes section headers to improve rendering of README on pkg.go.dev. 
Before (currently at https://pkg.go.dev/github.com/valyala/fasthttp@v1.58.0):
After merging this PR (https://pkg.go.dev/github.com/valyala/fasthttp@master):
=> docs: improve README formatting and section headers

args.go
Resolve #1856 
Since `Args` already contains a `buf` field, and multiple functions are designed to operate based on it, using the `buf` in `Args` results in a shorter process compared to using `bytebufferpool`. Additionally, based on the usage scenario, the number of calls to `SetUint` is unlikely to exceed 10, or even 100. Under such circumstances, using `buf` is significantly more efficient than `bytebufferpool`.
**Benchmark**
Call `SetUint` multiple times with the same key to compare the performance of the `AppendUint` step.
```go
func BenchmarkSetUint1(b *testing.B) {
benchmarkSetUint(b, 1)
}
func BenchmarkSetUint10(b *testing.B) {
benchmarkSetUint(b, 10)
}
func BenchmarkSetUint100(b *testing.B) {
benchmarkSetUint(b, 100)
}
func benchmarkSetUint(b *testing.B, n int) {
data := …
```
=> perf: use buf in Args instead of bytebufferpool

client_test.go, fasthttpproxy/dialer_test.go
Use github.com and .io instead of example.com and google.com as they are probably more reliable within Github actions.
=> Try to fix tests with dial timeouts

args.go, header.go
The original `trailer` field was represented by `[]argsKV`, where `argsKV` consisted of two `[]byte` slices and one `bool`, totaling **56** bytes. However, maintaining each element required only a single **24-byte** slice.
After refactoring, there was a significant reduction in memory usage.
I designed two benchmarks to compare the performance between the refactored code and the original implementation.
+ `BenchmarkSetTrailerBytes` primarily measures the performance of the `AddTrailerBytes` function.
+ `BenchmarkSetTrailerBytesWithReset` evaluates the efficiency of reusing memory by repeatedly adding trailers and resetting.
```go
func BenchmarkSetTrailerBytes(b *testing.B) {
list := make([][]byte, 5)
for i := range list {
list[i] = []byte(fmt.Sprintf("trailer-%d", i))
}
for i := 0; i < …
```
=> Refactor trailer Field for Improved Memory Efficiency and Performance

.gitignore, fs.go, fs_fs_test.go, fs_test.go
Before this PR, fasthttp would never use zstd if clients sent their `Accept-Encoding` header including gzip because zstd was the last option and would only be used if zstd was the only encoding available in `Accept-Encoding` header. This is really an issue when serving precompressed sidecars of zstd and gzip where the server preferred the latter.
The following order has been established; first brotli, then zstd, and finally gzip. It takes into account whether `CompressBrotli` and the new `CompressZstd` option are enabled to select which compression to use.
It also fixes the missing Vary header on compressed assets.
~~There is also an issue that has been revealed with the rework of these tests that should be addressed in a separate PR~~
=> fix: compression priority

tcplisten/socket.go, tcplisten/socket_other.go, tcplisten/tcplisten_js_wasm.go
@erikdubbelboer Can this be merged and a **new version be tagged**.
It is to support this: https://github.com/gofiber/fiber/issues/3298 & https://github.com/nlepage/go-wasm-http-server/issues/18
fasthttp wasn't building for `GOOS=js GOARCH=wasm go build` producing this build error:
```
../../go/pkg/mod/github.com/valyala/tcplisten@v1.0.0/socket_other.go:11:48: undefined: syscall.SOCK_NONBLOCK
../../go/pkg/mod/github.com/valyala/tcplisten@v1.0.0/socket_other.go:11:70: undefined: syscall.SOCK_CLOEXEC
```
=> add dummy support for js,wasm

args.go, header.go
The original `delAllArgs` method is stable but requires more copying operations to maintain the order of elements.
- Renamed the original `delAllArgs` method to `delAllArgsStable` to maintain stable behavior.
- Added a new `delAllArgs` method for non-stable functionality, improving runtime efficiency.
Depending on the specific use case:
+ Use `delAllArgsStable` when stability (order preservation) is required.
+ Use `delAllArgs` when stability is not necessary.
In the case of handling headers in `h.h`, the order of headers is not important. Refer to net/http [header.go](https://cs.opensource.google/go/go/+/refs/tags/go1.23.5:src/net/http/header.go;l=80-82;drc=4f0408a3a205a88624dced4b188e11dd429bc3ad), where the Del function calls [textproto.MIMEHeader.Del](https://cs.opensource.google/go/go …
=> perf: split delAllArgs into delAllArgs and delAllArgsStable

header.go, header_test.go, server_test.go
Fix #1917 
Make behavior consistent with `net/http` by allowing header keys and trailers containing spaces without canonicalizing them.
Change the behavior of `headerScanner.next()`. When parsing headers, we do not normalize the header key. 
In addition, before normalizing the key, check whether the key contains a space. If it does, disable normalization forcibly.
=> fix: accept invalid headers with a space

fuzz_test.go, header.go
The fuzzer found some cases where it would panic.
The output of normalizeHeaderValue doesn't need to affect s.b and s.hLen because the length of the normalized header will never be bigger, so it can just be normalize in place without affecting the rest of the buffer.
=> Fix normalizeHeaderValue

.github/workflows/test.yml, README.md, fs_fs_test.go, go.mod, go.sum, server.go, server_test.go
Some of our dependencies only support the officially supported Go versions by the Go team.
For example `github.com/golang/crypto` now requires 1.23 or higher. See: https://github.com/golang/crypto/commit/89ff08d67c4d79f9ac619aaf1f7388888798651fa
For more information on the new policy of the Go team see: https://github.com/golang/go/issues/69095
=> Update the supported version to the same as Go itself

server.go, server_test.go
Locking and unlocking a mutex multiple times per request is a major slowdown that we can avoid with clever use of atomics.
Before:
```
BenchmarkServerGet100ReqPerConn10KClients-12    	 84167428	       867.7 ns/op
```
After:
```
BenchmarkServerGet100ReqPerConn10KClients-12    	187397954	       386.3 ns/op
```
See: https://github.com/valyala/fasthttp/issues/1975
=> Remove idleConns mutex for every request

server.go, server_test.go, strings.go
Draft of Early Hints functionality.
Fixes: https://github.com/valyala/fasthttp/issues/1992
=> early hint functionality

http.go, http_test.go, streaming.go
This change adds support for streaming response bodies when the `Transfer-Encoding` is identity (or when `Content-Length` is not provided).
=> Add support for streaming identity-encoded or unknown length response bodies

http.go, server.go, server_test.go
Moving user values to Request structure is helpful to propagate context through many abstraction layers (e.g. for tracing/custom middlewares on client side).
Now it's impossible (or VERY awkward) to implement telemetry for client, since `Client.Do` have only request and response arguments.
It solves #940 and many other issues.
=> feat: move user values to Request structure

server.go
* add connKeepAliveer interface{}.
* use connKeepAliveer insteadof *net.TCPConn to set `TCPKeepalive` and `TCPKeepalivePeriod`.
I create a [rio](https://github.com/brickingsoft/rio) project, which is based on `IOURING`.
Because `rio.TCPConn` implmenets `net.Conn`, and has same functions as `net.TCPConn` had. 
For `rio` can be used as a network library for `FastHTTP`, so I create `connKeepAliveer` interface, use it to set `TCPKeepalive` and `TCPKeepalivePeriod`.
=> modify `acceptConn` for `RIO`

args.go, args_test.go, fasthttpadaptor/request.go, header.go, header_test.go
Resolves #2010
Create iterator for 
+ `Args.VisitAll` → `Args.All`
+ `ResponseHeader.VisitAll` → `ResponseHeader.All`
+ `ResponseHeader.VisitAllTrailer` → `ResponseHeader.Trailers`
+ `ResponseHeader.VisitAllCookie` → `ResponseHeader.Cookies`
+ `RequestHeader.VisitAll` → `RequestHeader.All`
+ `RequestHeader.VisitAllTrailer` → `RequestHeader.Trailers`
+ `RequestHeader.VisitAllCookie` → `RequestHeader.Cookies`
+ `RequestHeader.VisitAllInOrder` → `RequestHeader.AllInOrder`
=> feat: Add iter.Seq2 iterator

client.go
1. Simplify the Client.Do function, extract the acquisition of HostClient object into a separate function, and simplify the lock code
2. Remove redundant code from the AcquireReader and AcquireWriter functions of HostClient
=>  Simplify Client.Do function and lock usage

reuseport/reuseport.go, reuseport/reuseport_solaris.go
Copied from reuseport_aix.go to reuseport_solaris.go
SO_REUSEPORT is works on Solaris, but fails on illumos as intended.
I choose to avoid using tcplisten, because the unix.Listen from golang.org/x/sys/unix is currently broken.
=> Add reuseport support for Solaris

client_test.go, client_timing_test.go, coarsetime_test.go, server_timing_test.go, stackless/func_test.go, stackless/func_timing_test.go
This PR replaces atomic operations with atomic types for more type safety, better semantics, and clearer intent. Changes are done only in tests.
See https://cuonglm.xyz/post/go119_atomic_types/
=> test: replace atomic operations with atomic types

allocation_test.go, fs.go
When using caching fs shouldn't cause any allocations.
Only do []byte to string conversions when really needed. When a file is already cached the conversion shouldn't be needed.
Fixes https://github.com/valyala/fasthttp/issues/2045
=> Optimize fs to have 0 allocations

README.md
Adds [fasthttp-auth](https://github.com/casbin/fasthttp-auth) to the Related projects section in README.md.
[Casbin](https://github.com/casbin/casbin) is the most popular authorization library for Go with 400+ integrations across different frameworks and platforms.
[fasthttp-auth](https://github.com/casbin/fasthttp-auth) provides authorization middleware for fasthttp using Casbin, enabling developers to easily implement access control in their fasthttp applications.
Documentation update - no functional changes
=> docs: add fasthttp-auth to related projects section

client_test.go, tcpdialer.go
Resolves #2066
This commit introduces new methods for managing DNS cache in TCPDialer:
1. FlushDNSCache() - Clears all cached DNS entries, forcing fresh lookups
Key changes:
- Add FlushDNSCache() method to TCPDialer
- Add global FlushDNSCache() function for default dialer
- Refactor tcpAddrsClean() to extract reusable cleanExpiredDNSEntries() method
- Add comprehensive tests with mock resolver to verify caching behavior
Use case: Users can now set longer cache durations (e.g., 30 minutes) and manually refresh DNS when needed, providing better control over DNS resolution timing while maintaining performance benefits of caching.
=> Add DNS cache management methods for TCPDialer

http.go, http_test.go, server.go, server_test.go
Keep our server behaviour the same as net/http.
=> Reject backslash absolute URIs and cache parse errors
