compress.go
http.go

- Extracted some logic from `(Respone) BodyInflate` to WriteInflate replicated from WriteGunzip.
- Added `(Request) BodyInflate`

Added BodyInflate and WriteInflate to match BodyGunzip and WriteGunzip

---

README.md

Signed-off-by: Vishal Rana <vr@labstack.com>

Fixed Echo link

---

header.go
header_test.go
server.go
strings.go

I'm just about this short cosmetic fix. From my point of view DELETE popular enough to have own method IsDelete

Issue #107

---

fs.go
fs_test.go

Hi,
The bug raises when io.Writer passed to fsSmallFileReader.WriteTo doesn't support ReadFrom interface.
/link gavv/httpexpect#16

Add test for fsSmallFileReader.WriteTo and fix bug

---

status.go

Previous http status codes is not complete.

add missing http status codes

---

args.go

See: https://github.com/erikdubbelboer/fasthttp/pull/46

handle 't' and 'true' as bool in QueryArgs

---

client.go
client_test.go

See https://github.com/erikdubbelboer/fasthttp/pull/13

Fix bug that prevents custom user-agents

---

header_test.go

See: https://github.com/valyala/fasthttp/issues/238

Remove unreachable conditions

---

examples/multidomain/Makefile
examples/multidomain/README.md
examples/multidomain/multidomain.go
server.go
server_test.go

See: https://github.com/erikdubbelboer/fasthttp/pull/24

Added support for multiple TLS domains

---

server.go

Is already checked at https://github.com/valyala/fasthttp/blob/4a16377d6e780cb75b91962ea2100d83f7452565/http.go#L1190
and https://github.com/valyala/fasthttp/blob/4a16377d6e780cb75b91962ea2100d83f7452565/http.go#L1244
See: https://github.com/erikdubbelboer/fasthttp/pull/6/commits/eb05a47eae823055740d19b60a3144365b4eb4f7

Remove duplicate check

---

header.go

See: https://github.com/erikdubbelboer/fasthttp/pull/8

Add method to get cookie from response

---

client.go

Fixes: https://github.com/valyala/fasthttp/issues/308

Fix connsCleaner sleep time

---

fasthttpproxy/socks5.go

See: https://github.com/valyala/fasthttp/issues/161

Add SOCKS5 dialer

---

client_test.go
header.go
header_test.go
server_test.go

See https://github.com/valyala/fasthttp/issues/300

Don't suppresses TLS related errors

---

server.go
server_test.go

On Windows systems it is not possible to rename files that are opened.
See: https://github.com/valyala/fasthttp/issues/263

Close the file before trying to rename in SaveMultipartFile

---

header.go
header_test.go

See: https://github.com/valyala/fasthttp/issues/313

Fix Cookie peek

---

header.go
header_test.go
server.go

See https://github.com/valyala/fasthttp/pull/265 and https://github.com/valyala/fasthttp/issues/220 and https://github.com/valyala/fasthttp/issues/264

Fix Request.connectionCloseFast bugs

---

client.go
client_test.go
http.go

Related with the issue https://github.com/valyala/fasthttp/issues/244

Schema changes detection with HostClient

---

server.go

Fix Server.ConnState hook

---

server.go

Add note about `panic` recovery for `Server.Handler`

---

server.go

Update server to not release read and write buffers if `ReduceMemoryUsage` is not set

---

args.go
client.go
tcpdialer.go
timer.go

change timer to public api #525

---

tcpdialer.go

Make the max Dial concurrency limit configurable

---

client.go
client_test.go
cookie.go
http.go
http_test.go

add conn's address info in Response

---

server.go
server_test.go

add unit text
improve documentation
fix issue #541
better version of PR #542

fix context Err() issue

---

args_test.go
header.go
header_test.go
http_test.go
uri_test.go

when write test RequestCopyTO , i find rawHeadersCopy nocopy in ReqeustHeader's CopyTo. i add it.
is it a buf for no need copy?

add tests for copyto

---

server.go

Signed-off-by: Kirill Danshin <kirill@danshin.pro>

added option to keep hijacked connection open

---

server.go

Signed-off-by: Xiao YongBiao <xyb4638@gmail.com>

Fix comment.

---

.idea/.gitignore
client.go
client_test.go

Relates to https://github.com/valyala/fasthttp/issues/630

Add ability to set timeout for handshake

---

.travis.yml
README.md
fuzzit.sh
fuzzit/cookie/cookie_fuzz.go
fuzzit/request/request_fuzz.go
fuzzit/response/response_fuzz.go
fuzzit/url/url_fuzz.go

Add fuzzit support

---

args_test.go
bytesconv.go

This implementation similar to the official implementation but more faster, and it also fix some problems. See the previous pull request in https://github.com/valyala/fasthttp/pull/653

Improve appendQuotedPath and AppendQuotedArg

---

lbclient.go

See: https://github.com/valyala/fasthttp/issues/643
When we have multiple servers with the same amount of open requests it should pick the one who has handled the least total amount of requests.

Use least total requests instead of round robin for lbclient

---

README.md

Update "TechEmpower Benchmark" from round 12 to round 18

---

uri.go
uri_test.go

Fixes https://github.com/valyala/fasthttp/issues/701

Fix parsing relative URLs starting with //

---

header.go
header_test.go

- Replace tabs with spaces at line starts to match net/http
- Don't allow multi line header names. See: https://github.com/golang/go/issues/34702

Improve multiline header parsing

---

client.go
client_test.go
examples/multidomain/multidomain.go
fasthttputil/inmemory_listener.go
fs_test.go
header.go
server.go
server_test.go
tcpdialer.go

Resolve the remaining code issues on https://goreportcard.com/report/github.com/valyala/fasthttp.

Resolve code issues from goreportcard.com

---

server.go
server_test.go

You can use the following methods in the handler to find out which
listener the connection is coming in on.
```go
RequestCtx.IsTLS()
RequestCtx.LocalAddr()
RequestCtx.Request.Header.Host()
```

Support calling Serve multiple times on a Server

---

README.md
headers.go

`X-RequestedWith` => `X-Requested-With`

Fix XHR Typo

---

server.go

Currently, it appears that GetOpenConnectionsCount underreports the
count by 1 after Shutdown has been called. This leads to a confusing
value when servers are gracefully terminating. For instance, if a server
is stuck in graceful termination, and there is one open connection
keeping it alive, GetOpenConnectionsCount would report zero.
This fix removes the decrement while the server is shutting down. It is
not perfect due to the use of two sequential atomic loads, but in the
common case it should return a more correct value overall.

increase correctness of GetOpenConnectionsCount while Server is shutting down

---

README.md

Add third-party framework to README

---

fs.go
fs_test.go

Make FS return a redirect for directories without trailing slash

---

client.go
client_test.go

Hi,
The client will be able to use a custom retry decider with this pull request so the client will now be able to retry for non-idempotent requests.

Add custom retry decider for fail http requests

---

README.md

Round 19 of the TechEmpower Framework Benchmarks project is now available and this is the detailed blog: https://www.techempower.com/blog/2020/05/28/framework-benchmarks-round-19/

Update TechEmpower benchmark from 18 to 19 round

---

README.md

Gearbox is a web framework written in Go with a focus on high performance and memory optimization.

Added Gearbox

---

README.md

See https://github.com/buaazp/fasthttprouter/issues/55

update link to router package

---

http.go

func BodyUnbrotli and BodyUnbrotli have wrong comments. gzipped > brotlied

Fix comment typo

---

header.go

(header) do case insensitive lookup of cookie header value

---

header.go

Improve documentation about DelClientCookie

---

client.go

Fixing fix https://github.com/valyala/fasthttp/pull/975

Fix mCleaner not cleaning Ms fix.

---

client.go

This adds the `DisablePathNormalizing` bool that's present in `Client` but not in `PipelineClient`

Implemented DisablePathNormalizing in PipelineClient

---

fasthttpproxy/http.go

Add more response details in error message for fasthttpProxy

Format err info for proxy

---

.github/workflows/lint.yml

Fix golangci-lint action

---

http.go
server_test.go

Fix #1048 
Please take a look. @valyala @kirillDanshin 
Thanks.

fix: set content-length properly when StreanRequestBody was enabled

---

client.go

- Reduce mCleaner goroutine time.
- Add comment about changing Client fields while in use.

Fix Client doc and mCleaner

---

allocation_test.go
bytesconv_32.go
bytesconv_32_test.go
bytesconv_64.go
bytesconv_64_test.go
bytesconv_table_gen.go
client_timing_wait_test.go
fuzzit/cookie/cookie_fuzz.go
fuzzit/request/request_fuzz.go
fuzzit/response/response_fuzz.go
fuzzit/url/url_fuzz.go
reuseport/reuseport.go
uri_unix.go
uri_windows.go
uri_windows_test.go

as title , compatible with new build tag

compatible with new build tag

---

cookie.go

since  Cookie has been  cleared by  method `Reset` . i think it  is  unnecessary to  clear it ,  twice.

remove unnecessary  ` clear `

---

server.go

Added `MaxIdleWorkerDuration` to `Server`

Add MaxIdleWorkerDuration to Server.

---

fasthttpproxy/http.go

Add Host header fix behavior
https://datatracker.ietf.org/doc/html/rfc7230#section-5.4

Fix http proxy behavior

---

server.go

Hi, this patch aims to fix issue https://github.com/valyala/fasthttp/issues/1359

Fix(server): reset maxRequestBodySize to the server's config

---

fs.go
fs_test.go
header.go
header_test.go

Reverts valyala/fasthttp#1398
This introduced a bug in normal file serving: https://github.com/valyala/fasthttp/issues/1445

Revert "feat: support mulit/range"

---

bytesconv_table_gen.go
http_test.go

test: simplify bytes.Buffer declaration

---

lbclient.go

optimize:reduce loop

---

client.go
fasthttpadaptor/adaptor.go
fasthttpproxy/http.go

Update some codes style, maybe improve a little performance.

format : update some codes style

---

tcpdialer.go

https://github.com/valyala/fasthttp/issues/1581

Use timeout in TCPDialer to resolveTCPAddrs

---

client.go
server.go

This PR removes redundant indents.

Remove unnecessary indent blocks

---

fs.go
fs_test.go

this should fix #1472
related to https://github.com/gofiber/fiber/issues/2201

Skip fs cache based on config

---

.github/workflows/cifuzz.yml

Adds a workflow to run fasthttp's fuzzers in the CI.

Add CIFuzz

---

client.go

Currently, the conns length and connsCount count in HostClient do not correctly implement the MaxConns semaphore mechanism. This fix ensures that the waiter wake-up chain does not break.
See Issue: https://github.com/valyala/fasthttp/issues/1830

Fix the MaxConns semaphore issue in HostClient.

---

client.go

Sorry about that, I forgot to remove an unused field in previous pull rquest.

Sorry about forgetting to remove a redundant field and clarify the comments.

---

client.go

fix: Method-preserving doRequestFollowRedirects

---

README.md

related to https://github.com/valyala/fasthttp/issues/1914

add related project for opentelemetry-go-auto-instrumentation

---

tcpdialer.go

This PR fixes round robin addresses in dual stack dialing.
What and where is the best way to unit-test this fix?
- https://github.com/raviqqe/muffet/issues/449

Fix round robin addresses in dual stack dialing

---

peripconn.go

This happens when a perIPConn is idle and closed during Server.Shutdown() and then again closed by the WorkerFunc returning.
Fixes: https://github.com/valyala/fasthttp/issues/1987

Fix panic when perIPConn.Close is called multiple times

---

header.go
header_test.go

Fixes https://github.com/valyala/fasthttp/issues/2041

Fix RequestHeader.ContentLength() if disableSpecialHeader is true
